In [2]:
import numpy as np
import pandas as pd
pd.set_option('display.max_columns', None)  # Esto es para ver todas las columnas de un dataframe
pd.set_option('display.max_rows', None)     # Esto es para ver todas las filas de un dataframe

In [3]:
df = pd.read_csv('../datos/hr_raw_data_final.csv', index_col=0)

df.head()

age attrition businesstravel    dailyrate                department  \
0  51        No            NaN  2015.722222                       NaN   
1  52        No            NaN  2063.388889                       NaN   
2  42        No  travel_rarely  1984.253968   Research & Development    
3  47        No  travel_rarely  1771.404762                       NaN   
4  46        No            NaN  1582.771346                       NaN   

   distancefromhome  education    educationfield  employeecount  \
0                 6          3               NaN              1   
1                 1          4     Life Sciences              1   
2                 4          2  Technical Degree              1   
3                 2          4           Medical              1   
4                 3          3  Technical Degree              1   

   employeenumber  environmentsatisfaction  gender  hourlyrate  \
0               1                        1       0         NaN   
1               2                        3       0         NaN   
2               3                        3       0         NaN   
3               4                        1       1         NaN   
4               5                        1       1         NaN   

   jobinvolvement  joblevel              jobrole  jobsatisfaction  \
0               3         5   resEArch DIREcToR                 3   
1               2         5             ManAGeR                 3   
2               3         5             ManaGER                 4   
3               3         4   ReseArCH DIrECtOr                 3   
4               4         4     sAleS EXECUtIve                 1   

  maritalstatus monthlyincome monthlyrate  numcompaniesworked over18 overtime  \
0           NaN     16280,83$   42330,17$                   7      Y       No   
1           NaN           NaN   43331,17$                   0    NaN      NaN   
2       Married           NaN   41669,33$                   1    NaN       No   
3       Married     14307,50$   37199,50$                   3      Y      NaN   
4      Divorced     12783,92$   33238,20$                   2      Y       No   

   percentsalaryhike performancerating  relationshipsatisfaction  \
0                 13               3,0                         3   
1                 14               3,0                         1   
2                 11               3,0                         4   
3                 19               3,0                         2   
4                 12               3,0                         4   

  standardhours  stockoptionlevel totalworkingyears  trainingtimeslastyear  \
0     Full Time                 0               NaN                      5   
1           NaN                 1              34,0                      5   
2           NaN                 0              22,0                      3   
3     Full Time                 2               NaN                      2   
4           NaN                 1               NaN                      5   

  worklifebalance  yearsatcompany yearsincurrentrole  yearssincelastpromotion  \
0             3,0              20                NaN                       15   
1             3,0              33                NaN                       11   
2             NaN              22                NaN                       11   
3             NaN              20                NaN                        5   
4             3,0              19                NaN                        2   

   yearswithcurrmanager sameasmonthlyincome  datebirth      salary  \
0                    15           16280,83$       1972  195370,00$   
1                     9                 NaN       1971  199990,00$   
2                    15                 NaN       1981  192320,00$   
3                     6           14307,50$       1976  171690,00$   
4                     8           12783,92$       1977         NaN   

                        roledepartament  numberchildren remotework  
0     

In [4]:
# Columnas y filas
print(f"El número de filas que tenemos es {df.shape[0]}, y el número de columnas es {df.shape[1]}")

El número de filas que tenemos es 1678, y el número de columnas es 41


In [5]:
# Tamaño del Dataframe
df.size

68798

In [6]:
#utilizamos el metodo '.describe()' para sacar los principales estadísticos del DataFrame
# por defecto, nos devolverá solo los estadísticos de las VARIABLES NUMÉRICAS

df.describe()

dailyrate  distancefromhome    education  employeecount  \
count  1678.000000       1678.000000  1678.000000         1678.0   
mean    668.079714          4.504172     2.932658            1.0   
std     470.787298         14.652066     1.024270            0.0   
min     104.103175        -49.000000     1.000000            1.0   
25%     290.035510          2.000000     2.000000            1.0   
50%     556.256661          5.000000     3.000000            1.0   
75%     971.956349         11.000000     4.000000            1.0   
max    2063.388889         29.000000     5.000000            1.0   

       employeenumber  environmentsatisfaction       gender  hourlyrate  \
count     1678.000000              1678.000000  1678.000000  411.000000   
mean       809.859952                 4.264005     0.398689   83.140768   
std        467.084867                 6.912695     0.489774   57.272101   
min          1.000000                 1.000000     0.000000   13.012897   
25%        403.250000                 2.000000     0.000000   36.254439   
50%        813.500000                 3.000000     0.000000   69.532083   
75%       1215.750000                 4.000000     1.000000  116.987103   
max       1614.000000                49.000000     1.000000  255.963294   

       jobinvolvement     joblevel  jobsatisfaction  numcompaniesworked  \
count     1678.000000  1678.000000      1678.000000         1678.000000   
mean         2.740763     2.064362         2.743147            2.670441   
std          0.710359     1.099425         1.105172            2.501133   
min          1.000000     1.000000         1.000000            0.000000   
25%          2.000000     1.000000         2.000000            1.000000   
50%          3.000000     2.000000         3.000000            2.000000   
75%          3.000000     3.000000         4.000000            4.000000   
max          4.000000     5.000000         4.000000            9.000000   

       percentsalaryhike  relationshipsatisfaction  stockoptionlevel  \
count        1678.000000               1678.000000       1678.000000   
mean           15.154350                  2.700238          0.787843   
std             3.649607                  1.079494          0.843252   
min            11.000000                  1.000000          0.000000   
25%            12.000000                  2.000000          0.000000   
50%            14.000000                  3.000000          1.000000   
75%            18.000000                  4.000000          1.000000   
max            25.000000                  4.000000          3.000000   

       trainingtimeslastyear  yearsatcompany  yearssincelastpromotion  \
count            1678.000000     1678.000000              1678.000000   
mean                2.795590        7.124553                 2.241955   
std                 1.288657        6.173837                 3.246554   
min                 0.000000        0.000000                 0.000000   
25%                 2.000000        3.000000                 0.000000   
50%                 3.000000        5.000000                 1.000000   
75%                 3.000000        9.000000                 3.000000   
max                 6.000000       40.000000                15.000000   

       yearswithcurrmanager    datebirth  numberchildren  
count           1678.000000  1678.000000             0.0  
mean               4.200238  1986.047080             NaN  
std                3.554224     9.154908             NaN  
min                0.000000  1963.000000             NaN  
25%                2.000000  1980.000000             NaN  
50%                3.000000  1987.000000             NaN  
75%                7.000000  1993.000000             NaN  
max               17.000000  2005.000000             NaN

In [7]:
# podemos usar el método '.T' para transponer los resultados
df.describe().T

count         mean         std          min  \
dailyrate                 1678.0   668.079714  470.787298   104.103175   
distancefromhome          1678.0     4.504172   14.652066   -49.000000   
education                 1678.0     2.932658    1.024270     1.000000   
employeecount             1678.0     1.000000    0.000000     1.000000   
employeenumber            1678.0   809.859952  467.084867     1.000000   
environmentsatisfaction   1678.0     4.264005    6.912695     1.000000   
gender                    1678.0     0.398689    0.489774     0.000000   
hourlyrate                 411.0    83.140768   57.272101    13.012897   
jobinvolvement            1678.0     2.740763    0.710359     1.000000   
joblevel                  1678.0     2.064362    1.099425     1.000000   
jobsatisfaction           1678.0     2.743147    1.105172     1.000000   
numcompaniesworked        1678.0     2.670441    2.501133     0.000000   
percentsalaryhike         1678.0    15.154350    3.649607    11.000000   
relationshipsatisfaction  1678.0     2.700238    1.079494     1.000000   
stockoptionlevel          1678.0     0.787843    0.843252     0.000000   
trainingtimeslastyear     1678.0     2.795590    1.288657     0.000000   
yearsatcompany            1678.0     7.124553    6.173837     0.000000   
yearssincelastpromotion   1678.0     2.241955    3.246554     0.000000   
yearswithcurrmanager      1678.0     4.200238    3.554224     0.000000   
datebirth                 1678.0  1986.047080    9.154908  1963.000000   
numberchildren               0.0          NaN         NaN          NaN   

                                  25%          50%          75%          max  
dailyrate                  290.035510   556.256661   971.956349  2063.388889  
distancefromhome             2.000000     5.000000    11.000000    29.000000  
education                    2.000000     3.000000     4.000000     5.000000  
employeecount                1.000000     1.000000     1.000000     1.000000  
employeenumber             403.250000   813.500000  1215.750000  1614.000000  
environmentsatisfaction      2.000000     3.000000     4.000000    49.000000  
gender                       0.000000     0.000000     1.000000     1.000000  
hourlyrate                  36.254439    69.532083   116.987103   255.963294  
jobinvolvement               2.000000     3.000000     3.000000     4.000000  
joblevel                     1.000000     2.000000     3.000000     5.000000  
jobsatisfaction              2.000000     3.000000     4.000000     4.000000  
numcompaniesworked           1.000000     2.000000     4.000000     9.000000  
percentsalaryhike           12.000000    14.000000    18.000000    25.000000  
relationshipsatisfaction     2.000000     3.000000     4.000000     4.000000  
stockoptionlevel             0.000000     1.000000     1.000000     3.000000  
trainingtimeslastyear        2.000000     3.000000     3.000000     6.000000  
yearsatcompany               3.000000     5.000000     9.000000    40.000000  
yearssincelastpromotion      0.000000     1.000000     3.000000    15.000000  
yearswithcurrmanager         2.000000     3.000000     7.000000    17.000000  
datebirth                 1980.000000  1987.000000  1993.000000  2005.000000  
numberchildren                    NaN          NaN          NaN          NaN

In [8]:
# hagamos lo mismo para las columnas categóricas, para eso tendremos que incluir entre los paréntesis el parámetro include = "object"
df.describe(include = "object").T

count unique  \
age                  1678     54   
attrition            1678      2   
businesstravel        877      3   
department            312      3   
educationfield        904      6   
jobrole              1678   1579   
maritalstatus        1003      5   
monthlyincome        1189    493   
monthlyrate          1678    673   
over18                740      1   
overtime              982      2   
performancerating    1478      2   
standardhours        1327      2   
totalworkingyears    1129     40   
worklifebalance      1564      4   
yearsincurrentrole     35     10   
sameasmonthlyincome  1189    493   
salary               1393    583   
roledepartament       312    301   
remotework           1678      5   

                                                                 top  freq  
age                                                               35    88  
attrition                                                         No  1406  
businesstravel                                         travel_rarely   616  
department                                   Research & Development    203  
educationfield                                         Life Sciences   367  
jobrole                                                     mANager      5  
maritalstatus                                                Married   419  
monthlyincome                                               2342,59$   228  
monthlyrate                                                11681,39$   326  
over18                                                             Y   740  
overtime                                                          No   714  
performancerating                                                3,0  1257  
standardhours                                              Part Time   927  
totalworkingyears                                               10,0   151  
worklifebalance                                                  3,0   946  
yearsincurrentrole                                               2,0    12  
sameasmonthlyincome                                         2342,59$   228  
salary                                                     53914,11$   270  
roledepartament       rESEArcH SCiEntIst  -  Research & Development      2  
remotework                                                         1   375

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1678 entries, 0 to 1677
Data columns (total 41 columns):
 #   Column                    Non-Null Count  Dtype  
---  ------                    --------------  -----  
 0   age                       1678 non-null   object 
 1   attrition                 1678 non-null   object 
 2   businesstravel            877 non-null    object 
 3   dailyrate                 1678 non-null   float64
 4   department                312 non-null    object 
 5   distancefromhome          1678 non-null   int64  
 6   education                 1678 non-null   int64  
 7   educationfield            904 non-null    object 
 8   employeecount             1678 non-null   int64  
 9   employeenumber            1678 non-null   int64  
 10  environmentsatisfaction   1678 non-null   int64  
 11  gender                    1678 non-null   int64  
 12  hourlyrate                411 non-null    float64
 13  jobinvolvement            1678 non-null   int64  
 14  joblevel     

In [10]:
# Todas las columnas
df.columns

Index(['age', 'attrition', 'businesstravel', 'dailyrate', 'department',
       'distancefromhome', 'education', 'educationfield', 'employeecount',
       'employeenumber', 'environmentsatisfaction', 'gender', 'hourlyrate',
       'jobinvolvement', 'joblevel', 'jobrole', 'jobsatisfaction',
       'maritalstatus', 'monthlyincome', 'monthlyrate', 'numcompaniesworked',
       'over18', 'overtime', 'percentsalaryhike', 'performancerating',
       'relationshipsatisfaction', 'standardhours', 'stockoptionlevel',
       'totalworkingyears', 'trainingtimeslastyear', 'worklifebalance',
       'yearsatcompany', 'yearsincurrentrole', 'yearssincelastpromotion',
       'yearswithcurrmanager', 'sameasmonthlyincome', 'datebirth', 'salary',
       'roledepartament', 'numberchildren', 'remotework'],
      dtype='object')

In [11]:
# Tipos de datos de cada columna

df.dtypes

age                          object
attrition                    object
businesstravel               object
dailyrate                   float64
department                   object
distancefromhome              int64
education                     int64
educationfield               object
employeecount                 int64
employeenumber                int64
environmentsatisfaction       int64
gender                        int64
hourlyrate                  float64
jobinvolvement                int64
joblevel                      int64
jobrole                      object
jobsatisfaction               int64
maritalstatus                object
monthlyincome                object
monthlyrate                  object
numcompaniesworked            int64
over18                       object
overtime                     object
percentsalaryhike             int64
performancerating            object
relationshipsatisfaction      int64
standardhours                object
stockoptionlevel            

In [12]:
# sacamos las columnas que son de tipo object (categóricas) de nuestro DataFrame usando el método '.select_dtypes()'
df_cat = df.select_dtypes(include = "object")
df_cat.head()

age attrition businesstravel                department    educationfield  \
0  51        No            NaN                       NaN               NaN   
1  52        No            NaN                       NaN     Life Sciences   
2  42        No  travel_rarely   Research & Development   Technical Degree   
3  47        No  travel_rarely                       NaN           Medical   
4  46        No            NaN                       NaN  Technical Degree   

               jobrole maritalstatus monthlyincome monthlyrate over18  \
0   resEArch DIREcToR            NaN     16280,83$   42330,17$      Y   
1             ManAGeR            NaN           NaN   43331,17$    NaN   
2             ManaGER        Married           NaN   41669,33$    NaN   
3   ReseArCH DIrECtOr        Married     14307,50$   37199,50$      Y   
4     sAleS EXECUtIve       Divorced     12783,92$   33238,20$      Y   

  overtime performancerating standardhours totalworkingyears worklifebalance  \
0       No               3,0     Full Time               NaN             3,0   
1      NaN               3,0           NaN              34,0             3,0   
2       No               3,0           NaN              22,0             NaN   
3      NaN               3,0     Full Time               NaN             NaN   
4       No               3,0           NaN               NaN             3,0   

  yearsincurrentrole sameasmonthlyincome      salary  \
0                NaN           16280,83$  195370,00$   
1                NaN                 NaN  199990,00$   
2                NaN                 NaN  192320,00$   
3                NaN           14307,50$  171690,00$   
4                NaN           12783,92$         NaN   

                        roledepartament remotework  
0                                   NaN        Yes  
1                                   NaN          1  
2   ManaGER  -  Research & Development           1  
3                                   NaN      False  
4                                   NaN          0

In [13]:
# inplace = True porque queremos que los cambios realizados se sobreescriban en el DataFrame
df_cat.drop(['monthlyincome', 'monthlyrate', 'performancerating', 'totalworkingyears' , 'worklifebalance', 'sameasmonthlyincome', 'salary', 'age'], axis = 1, inplace=True)
# chuequeamos como se ha quedado el DataFrame y vemos que ya lo tenemos preparado para poder evaluar cuales son sus valores únicos ('.unique()') y sus frecuencias ('.value_counts()')
df_cat.head()

attrition businesstravel                department    educationfield  \
0        No            NaN                       NaN               NaN   
1        No            NaN                       NaN     Life Sciences   
2        No  travel_rarely   Research & Development   Technical Degree   
3        No  travel_rarely                       NaN           Medical   
4        No            NaN                       NaN  Technical Degree   

               jobrole maritalstatus over18 overtime standardhours  \
0   resEArch DIREcToR            NaN      Y       No     Full Time   
1             ManAGeR            NaN    NaN      NaN           NaN   
2             ManaGER        Married    NaN       No           NaN   
3   ReseArCH DIrECtOr        Married      Y      NaN     Full Time   
4     sAleS EXECUtIve       Divorced      Y       No           NaN   

  yearsincurrentrole                       roledepartament remotework  
0                NaN                                   NaN        Yes  
1                NaN                                   NaN          1  
2                NaN   ManaGER  -  Research & Development           1  
3                NaN                                   NaN      False  
4                NaN                                   NaN          0

In [14]:
# creamos una variable con los nombres de las columnas del DataFrame de las variables categóricas utilizando el método '.columns'
columnas_cat = df_cat.columns
print(f"Las columnas del DataFrame de variables categóricas son {columnas_cat}")

# empezamos a iterar por cada una de las columnas para sacar sus valores únicos y sus frecuencias
for columna in columnas_cat:
    print(f" \n----------- ESTAMOS ANALIZANDO LA COLUMNA: '{columna.upper()}' -----------\n")
    print(f"Sus valores únicos son: {df_cat[columna].unique()}\n")
    print(f"Las frecuencias de los valores únicos de las categorías son: {df_cat[columna].value_counts()} ")
    print(f"Cantidad de valores nulos: {df_cat[columna].isna().sum()}")

Las columnas del DataFrame de variables categóricas son Index(['attrition', 'businesstravel', 'department', 'educationfield',
       'jobrole', 'maritalstatus', 'over18', 'overtime', 'standardhours',
       'yearsincurrentrole', 'roledepartament', 'remotework'],
      dtype='object')
 
----------- ESTAMOS ANALIZANDO LA COLUMNA: 'ATTRITION' -----------

Sus valores únicos son: ['No' 'Yes']

Las frecuencias de los valores únicos de las categorías son: attrition
No     1406
Yes     272
Name: count, dtype: int64 
Cantidad de valores nulos: 0
 
----------- ESTAMOS ANALIZANDO LA COLUMNA: 'BUSINESSTRAVEL' -----------

Sus valores únicos son: [nan 'travel_rarely' 'travel_frequently' 'non-travel']

Las frecuencias de los valores únicos de las categorías son: businesstravel
travel_rarely        616
travel_frequently    168
non-travel            93
Name: count, dtype: int64 
Cantidad de valores nulos: 801
 
----------- ESTAMOS ANALIZANDO LA COLUMNA: 'DEPARTMENT' -----------

Sus valores únicos so

In [15]:
# Cantidad de nulos que hay por columnas
nulos_columnas = df.isna().sum()

# El total de nulos en todas las columnas
total_nulos = nulos_columnas.sum()

porcentaje = ((nulos_columnas/total_nulos) *100).round(2)

print(f' El porcetaje que cada columna tiene de nulo es de: \n {porcentaje}')

 El porcetaje que cada columna tiene de nulo es de: 
 age                          0.00
attrition                    0.00
businesstravel               5.85
dailyrate                    0.00
department                   9.98
distancefromhome             0.00
education                    0.00
educationfield               5.66
employeecount                0.00
employeenumber               0.00
environmentsatisfaction      0.00
gender                       0.00
hourlyrate                   9.26
jobinvolvement               0.00
joblevel                     0.00
jobrole                      0.00
jobsatisfaction              0.00
maritalstatus                4.93
monthlyincome                3.57
monthlyrate                  0.00
numcompaniesworked           0.00
over18                       6.86
overtime                     5.09
percentsalaryhike            0.00
performancerating            1.46
relationshipsatisfaction     0.00
standardhours                2.57
stockoptionlevel            

In [16]:
# Código nos esta diciendo que no tenemos filas duplicadas
df.duplicated().sum()

64

In [17]:
# si por ejemplo evaluaramos si existen valores duplicados para la columna de 'id_' debería salir que no existe ningún valor duplicado, ya que estos id deberían ser únicos
# usemos de nuevo el parámetro 'subset'
df.duplicated(subset  = "employeenumber").sum() 

64

In [18]:
df['gender'].unique()
df['gender'].value_counts()

gender
0    1009
1     669
Name: count, dtype: int64

In [19]:
df['environmentsatisfaction'].unique()

array([ 1,  3,  4,  2, 42, 37, 35, 25, 27, 31, 39, 21, 15, 14, 33, 19, 12,
       13, 28, 47, 36, 29, 24, 46, 16, 22, 41, 49, 11, 48, 18, 10, 45, 38,
       17, 20, 26, 43])

In [20]:
df['employeenumber'].unique()

array([   1,    2,    3, ..., 1612, 1613, 1614])

In [21]:
df['employeecount'].unique()

array([1])

In [22]:
df['educationfield'].unique()

array([nan, 'Life Sciences', 'Technical Degree', 'Medical', 'Other',
       'Marketing', 'Human Resources'], dtype=object)

In [23]:
# Valores unicos de la columna 'AGE'

df['age'].unique()

array(['51', '52', '42', '47', '46', '48', '59', '41', '56', '38', '55',
       '40', '58', '35', '45', '33', '36', '34', 'forty-seven', '53',
       '43', '60', '32', '37', '49', '39', '50', '44', '30',
       'fifty-eight', '29', '31', '54', '57', '27', 'thirty-six', '28',
       '26', 'fifty-five', '25', 'fifty-two', 'thirty-one', '24',
       'thirty', '23', '22', '21', '20', 'twenty-six', '19',
       'thirty-seven', '18', 'thirty-two', 'twenty-four'], dtype=object)

In [24]:

df['attrition'].unique()

array(['No', 'Yes'], dtype=object)

In [25]:
df['businesstravel'].unique()

array([nan, 'travel_rarely', 'travel_frequently', 'non-travel'],
      dtype=object)

In [26]:
df['dailyrate'].unique()

array([2015.72222222, 2063.38888889, 1984.25396825, 1771.4047619 ,
       1582.77134647, 1771.92063492, 1032.48728618,  556.256661  ,
       1712.18253968, 1973.98412698, 2060.70634921, 1382.74603175,
       1362.52380952, 2016.54761905, 1861.37301587, 1985.6984127 ,
       1108.92063492, 1728.38095238,  639.78571429, 2047.5       ,
        412.8015873 , 1077.86507937, 1657.3968254 ,  331.19047619,
       1059.19047619, 1080.75396825,  635.76190476,  487.08730159,
        290.03550974,  476.15079365, 1749.73809524, 1063.31746032,
        557.76190476,  608.93650794, 1119.96031746,  610.17460317,
        685.6984127 , 1441.65873016, 1374.28571429,  689.92857143,
        488.53174603, 1431.23809524, 1964.96031746, 1652.34126984,
        991.81746032, 1187.53968254,  444.26984127, 1758.71428571,
        522.78571429,  380.92063492, 2047.70634921,  238.12698413,
        592.94444444, 1075.28571429,  654.84920635,  242.25396825,
        316.95238095, 1288.65079365,  827.46031746, 1760.98412

In [27]:
df['department'].unique()

array([nan, ' Research & Development ', ' Sales ', ' Human Resources '],
      dtype=object)

In [28]:
df['distancefromhome'].unique()

array([  6,   1,   4,   2,   3,  22,  25,   9,   7,  23,  10,  12,  14,
       -13,  15,   8, -42,  28, -37,   5,  16, -35,  26, -26,  24,  29,
       -25,  17,  21, -18, -10, -30, -27,  20, -31, -29, -39,  18, -21,
       -15,  11,  13, -14,  19, -33, -34, -46, -36, -19,  27, -12, -23,
       -45, -28, -47, -32, -24, -16, -22, -41, -49, -11, -48, -38, -20,
       -17, -43, -40, -44])

In [29]:
df['education'].unique()

array([3, 4, 2, 1, 5])

In [30]:
df['hourlyrate'].unique()

array([         nan,  69.53208262, 172.84325397, 216.04761905,
        79.97321429, 129.06091077, 246.74801587, 207.17460317,
        60.8859127 ,  36.25443872, 139.99503968,  86.24107143,
       197.84641831,  61.06646825, 245.62003968, 123.97718254,
       148.44246032, 255.96329365, 134.41071429,  71.92559524,
       113.78869048, 175.10019841, 247.49007937, 220.83234127,
        91.34821429,  37.77480159, 198.9593254 , 124.05456349,
       247.58035714, 108.48809524,  43.17857143,  68.46924603,
        32.48710317,  55.26289683,  83.46825397,  79.26388889,
        72.28670635,  45.96428571,  31.66170635,  65.19345238,
        52.24503968, 143.9156746 , 113.40178571, 143.19345238,
       139.86607143,  70.57142857,  97.04861111,  45.02281746,
       223.47619048, 134.9781746 ,  74.40178571,  67.14087302,
        58.06150794,  35.05357143,  73.18948413, 164.33134921,
        43.53968254,  54.79861111, 252.59722222,  83.81646825,
        46.71230159,  33.00297619,  70.77777778,  69.23

In [31]:
df['jobinvolvement'].unique()

array([3, 2, 4, 1])

In [32]:
df['joblevel'].unique()

array([5, 4, 3, 2, 1])

In [33]:
df['jobsatisfaction'].unique()

array([3, 4, 1, 2])

In [34]:
df['numcompaniesworked'].unique()

array([7, 0, 1, 3, 2, 4, 8, 9, 5, 6])

In [35]:
df['over18'].unique()

array(['Y', nan], dtype=object)

In [36]:
df['overtime'].unique()

array(['No', nan, 'Yes'], dtype=object)

In [37]:
df['percentsalaryhike'].unique()

array([13, 14, 11, 19, 12, 25, 16, 17, 22, 23, 20, 15, 21, 24, 18])

In [38]:
df['performancerating'].unique()

array(['3,0', '4,0', nan], dtype=object)

In [39]:
df['relationshipsatisfaction'].unique()

array([3, 1, 4, 2])

In [40]:
df['standardhours'].unique()

array(['Full Time', nan, 'Part Time'], dtype=object)

In [41]:
df['stockoptionlevel'].unique()

array([0, 1, 2, 3])

In [42]:
df['totalworkingyears'].unique()

array([nan, '34,0', '22,0', '28,0', '20,0', '21,0', '33,0', '40,0',
       '18,0', '25,0', '15,0', '17,0', '26,0', '16,0', '24,0', '14,0',
       '23,0', '27,0', '19,0', '11,0', '38,0', '37,0', '13,0', '12,0',
       '29,0', '10,0', '36,0', '35,0', '9,0', '31,0', '32,0', '8,0',
       '7,0', '30,0', '6,0', '5,0', '4,0', '3,0', '2,0', '1,0', '0,0'],
      dtype=object)

In [43]:
df['trainingtimeslastyear'].unique()

array([5, 3, 2, 0, 1, 4, 6])

In [44]:
df['worklifebalance'].unique()

array(['3,0', nan, '2,0', '4,0', '1,0'], dtype=object)

In [45]:
df['yearsatcompany'].unique()

array([20, 33, 22, 19, 21, 18, 24, 31, 26, 16, 23, 15, 17, 32, 14, 13, 25,
       12, 11, 37, 40, 36, 27, 29, 10,  9, 30,  8,  7, 34,  6,  5,  4,  2,
        3,  1,  0])

In [46]:
df['yearsincurrentrole'].unique()

array([nan, '13,0', '12,0', '11,0', '7,0', '6,0', '4,0', '3,0', '2,0',
       '1,0', '0,0'], dtype=object)

In [47]:
df['yearssincelastpromotion'].unique()

array([15, 11,  5,  2,  4,  7,  0,  1, 13, 14,  8, 12,  3,  6, 10,  9])

In [48]:
df['yearswithcurrmanager'].unique()

array([15,  9,  6,  8,  7, 11, 10, 12,  4,  0,  5, 17,  2, 14,  1, 13,  3,
       16])

In [49]:
df['sameasmonthlyincome'].unique()

array(['16280,83$', nan, '14307,50$', '12783,92$', '14311,67$',
       '8339,32$', '13829,17$', '15943,72$', '16644,17$', '15034,17$',
       '16038,33$', '4492,84$', '8956,67$', '5167,50$', '3334,17$',
       '8705,83$', '2675,00$', '8555,00$', '8729,17$', '3934,17$',
       '3845,83$', '14132,50$', '8588,33$', '4505,00$', '4918,33$',
       '4928,33$', '5538,33$', '11100,00$', '5572,50$', '11560,00$',
       '15870,83$', '13345,83$', '8010,83$', '3588,33$', '14205,00$',
       '4222,50$', '3076,67$', '2342,59$', '4789,17$', '8685,00$',
       '5289,17$', '1956,67$', '10408,33$', '6683,33$', '7452,50$',
       '16060,00$', '4647,50$', '2242,50$', '6169,17$', '7352,50$',
       '2982,50$', '14815,83$', '15177,50$', '15991,67$', '15989,17$',
       '8340,00$', '6656,67$', '5902,50$', '3935,83$', '2839,17$',
       '2440,83$', '10025,83$', '12855,83$', '5135,00$', '4271,67$',
       '8015,83$', '4175,00$', '15860,83$', '8666,67$', '2327,50$',
       '4728,33$', '7010,00$', '2790,00$', '4

In [50]:
df['datebirth'].unique()

array([1972, 1971, 1981, 1976, 1977, 1975, 1964, 1982, 1967, 1985, 1968,
       1983, 1965, 1988, 1978, 1990, 1987, 1989, 1970, 1980, 1963, 1991,
       1986, 1974, 1984, 1973, 1979, 1993, 1994, 1992, 1969, 1966, 1996,
       1995, 1997, 1998, 1999, 2000, 2001, 2002, 2003, 2004, 2005])

In [51]:
df['salary'].unique()

array(['195370,00$', '199990,00$', '192320,00$', '171690,00$', nan,
       '100071,84$', '53914,11$', '165950,00$', '199730,00$',
       '134020,00$', '132060,00$', '195450,00$', '180410,00$',
       '192460,00$', '107480,00$', '167520,00$', '62010,00$',
       '198450,00$', '40010,00$', '104470,00$', '191324,62$',
       '160640,00$', '32100,00$', '102660,00$', '104750,00$', '61620,00$',
       '47210,00$', '153407,07$', '28111,13$', '46150,00$', '169590,00$',
       '54060,00$', '59020,00$', '108550,00$', '59140,00$', '66460,00$',
       '139730,00$', '66870,00$', '47350,00$', '138720,00$', '190450,00$',
       '96130,00$', '115100,00$', '170460,00$', '36920,00$', '198470,00$',
       '23080,00$', '57470,00$', '104220,00$', '63470,00$', '23480,00$',
       '30720,00$', '124900,00$', '80200,00$', '170680,00$', '89430,00$',
       '192720,00$', '55770,00$', '26910,00$', '74030,00$', '88230,00$',
       '35790,00$', '177790,00$', '182130,00$', '135770,00$',
       '191900,00$', '171230,

In [52]:
df['roledepartament'].unique()

array([nan, ' ManaGER  -  Research & Development ',
       ' MANAger  -  Research & Development ',
       ' heaLtHcArE repResENtATiVe  -  Research & Development ',
       ' saLEs exEcutIVe  -  Sales ', ' Sales ExECuTIVe  -  Sales ',
       ' heALthCArE RePResEntaTIVe  -  Research & Development ',
       ' lABORAtOry tECHnIcIan  -  Research & Development ',
       ' ManufactUrINg DiReCTOr  -  Research & Development ',
       ' SaleS eXEcUtIVE  -  Sales ',
       ' HEaLthcaRe rEprEsEnTAtiVe  -  Research & Development ',
       ' rESeArCH sCientIST  -  Research & Development ',
       ' healTHCAre rePREseNtATiVE  -  Research & Development ',
       ' mANaGer  -  Research & Development ',
       ' HEAltHCaRe REPreseNTatIve  -  Research & Development ',
       ' SaLeS eXECUTivE  -  Sales ',
       ' reSeARCH SCIEnTiST  -  Research & Development ',
       ' ReSearch DiRecTOR  -  Research & Development ',
       ' resEaRCh SciEnTist  -  Research & Development ',
       ' hUmaN REsoUrCes  -  H

In [53]:
df['numberchildren'].unique()

array([nan])

In [54]:
df['remotework'].unique()

array(['Yes', '1', 'False', '0', 'True'], dtype=object)

In [55]:
# Metodo para cambiar el tipo de una columna

# df['age'].astype(int)

#FASE 2:

- **Fase 2: Transformación de los datos.**  

    Esto puede incluir la limpieza de datos, la normalización, la conversión de tipos de datos y la aplicación de reglas empresariales específicas. Las transformaciones se realizarán mediante funciones de Python que se aplicarán a los datos extraídos. Algunas de las transformaciones que podrías hacer son: 

    - La columna `Gender` tiene valores de 0 y 1, los cuales son pocos intutitivos. Los podrías reemplazar por "Male" y "Female", o "M" y "F" por ejemplo. 

    - Algunas columnas, como la columna `DailyRate` son columnas que incluyen valores numéricos decimales. Pero en el DataFrame aparece como columna de tipo string. Deberás hacer los cambios necesarios para convertirla en columna de tipo numérica. 

    - Evaluar si hay valores duplicados y analizar si tiene sentido eliminarlos o mantenerlos. 

    - Valores inconsistentes, por ejemplo en la columna `DistanceFromHome` tiene valores negativos. 

    - Errores tipográficos en algunos valores de las columnas categóricas. Por ejemplo, en la columna `MaritalStatus` en vez de "Married" en algunas filas aparece "Marreid". 

    - Columnas redundantes, es decir, columnas que nos dan la misma información expresada de forma diferente.

In [56]:
#La columna `Gender` tiene valores de 0 y 1, los cuales son pocos intutitivos. Los podrías reemplazar por "Male" y "Female", o "M" y "F" por ejemplo. 

In [57]:
# Reemplazar valores en la columna 'Gender'
# Supongamos que 1 representa 'Male' y 0 representa 'Female'
df['gender'] = df['gender'].replace({1: 'Male', 0: 'Female'})


df['gender']

0       Female
1       Female
2       Female
3         Male
4         Male
         ...  
1673      Male
1674      Male
1675    Female
1676      Male
1677      Male
Name: gender, Length: 1678, dtype: object

 Algunas columnas, como la columna `DailyRate` son columnas que incluyen valores numéricos decimales. Pero en el DataFrame aparece como columna de tipo string. Deberás hacer los cambios necesarios para convertirla en columna de tipo numérica.

In [59]:
# Convertir la columna 'DailyRate' de string a tipo numérico (float)
df['dailyrate'] = pd.to_numeric(df['dailyrate'], errors='coerce')
df['dailyrate']

0       2015.722222
1       2063.388889
2       1984.253968
3       1771.404762
4       1582.771346
           ...     
1673     488.944444
1674    1973.984127
1675     290.035510
1676    1032.487286
1677     556.256661
Name: dailyrate, Length: 1678, dtype: float64

In [60]:
# Comprobar si hay valores nulos
null_values = df['dailyrate'].isnull().sum()
print(f"Valores nulos en 'dailyrate': {null_values}")


Valores nulos en 'dailyrate': 0


In [61]:
# Comprobar si hay valores nulos
null_values = df['gender'].isnull().sum()
print(f"Valores nulos en 'gender': {null_values}")

Valores nulos en 'gender': 0


In [62]:
#Evaluar si hay valores duplicados y analizar si tiene sentido eliminarlos o mantenerlos. 
pd.set_option('display.max_columns', None) # para poder visualizar todas las columnas de los DataFrames
df.head()

age attrition businesstravel    dailyrate                department  \
0  51        No            NaN  2015.722222                       NaN   
1  52        No            NaN  2063.388889                       NaN   
2  42        No  travel_rarely  1984.253968   Research & Development    
3  47        No  travel_rarely  1771.404762                       NaN   
4  46        No            NaN  1582.771346                       NaN   

   distancefromhome  education    educationfield  employeecount  \
0                 6          3               NaN              1   
1                 1          4     Life Sciences              1   
2                 4          2  Technical Degree              1   
3                 2          4           Medical              1   
4                 3          3  Technical Degree              1   

   employeenumber  environmentsatisfaction  gender  hourlyrate  \
0               1                        1  Female         NaN   
1               2                        3  Female         NaN   
2               3                        3  Female         NaN   
3               4                        1    Male         NaN   
4               5                        1    Male         NaN   

   jobinvolvement  joblevel              jobrole  jobsatisfaction  \
0               3         5   resEArch DIREcToR                 3   
1               2         5             ManAGeR                 3   
2               3         5             ManaGER                 4   
3               3         4   ReseArCH DIrECtOr                 3   
4               4         4     sAleS EXECUtIve                 1   

  maritalstatus monthlyincome monthlyrate  numcompaniesworked over18 overtime  \
0           NaN     16280,83$   42330,17$                   7      Y       No   
1           NaN           NaN   43331,17$                   0    NaN      NaN   
2       Married           NaN   41669,33$                   1    NaN       No   
3       Married     14307,50$   37199,50$                   3      Y      NaN   
4      Divorced     12783,92$   33238,20$                   2      Y       No   

   percentsalaryhike performancerating  relationshipsatisfaction  \
0                 13               3,0                         3   
1                 14               3,0                         1   
2                 11               3,0                         4   
3                 19               3,0                         2   
4                 12               3,0                         4   

  standardhours  stockoptionlevel totalworkingyears  trainingtimeslastyear  \
0     Full Time                 0               NaN                      5   
1           NaN                 1              34,0                      5   
2           NaN                 0              22,0                      3   
3     Full Time                 2               NaN                      2   
4           NaN                 1               NaN                      5   

  worklifebalance  yearsatcompany yearsincurrentrole  yearssincelastpromotion  \
0             3,0              20                NaN                       15   
1             3,0              33                NaN                       11   
2             NaN              22                NaN                       11   
3             NaN              20                NaN                        5   
4             3,0              19                NaN                        2   

   yearswithcurrmanager sameasmonthlyincome  datebirth      salary  \
0                    15           16280,83$       1972  195370,00$   
1                     9                 NaN       1971  199990,00$   
2                    15                 NaN       1981  192320,00$   
3                     6           14307,50$       1976  171690,00$   
4                     8           12783,92$       1977         NaN   

                        roledepartament  numberchildren remotework  
0     

In [63]:
# ¿tenemos duplicados teniendo en cuenta todas las filas del DataFrame?
# al igual que en el caso del '.isnull()' nos devuelve una serie de Booleanos
df.duplicated()

0       False
1       False
2       False
3       False
4       False
        ...  
1673     True
1674     True
1675     True
1676     True
1677     True
Length: 1678, dtype: bool

In [64]:
# como hemos visto lo anterior nos devuelve una serie de booleanos lo cual es poco entendible, 
# por lo que añadiremos el método '.sum()' para que nos cuente cuantas filas tenemos duplicadas

df.duplicated().sum()

64

In [65]:
#Evaluar si hay valores duplicados y analizar si tiene sentido eliminarlos o mantenerlos. 
#Valores inconsistentes, por ejemplo en la columna `DistanceFromHome` tiene valores negativos.

# Verifico duplicados
duplicados = df.duplicated().sum()
print(f"Número de registros duplicados: {duplicados}")

Número de registros duplicados: 64


In [ ]:
# Cambiar los valores de distancia from home a un modulo, o sea, no tener más los negativos

PR = df["distancefromhome"] = df["distancefromhome"].abs()
PR

0        6
1        1
2        4
3        2
4        3
        ..
1673    26
1674    26
1675    15
1676     4
1677     2
Name: distancefromhome, Length: 1678, dtype: int64

In [ ]:
# Verificar si hay valores negativos en DistanceFromHome
#inconsistentes = df[df['distancefromhome'] < 0]
#print("Registros con valores negativos en 'distancefromhome':")
#print(inconsistentes)


Registros con valores negativos en 'distancefromhome':
     age attrition     businesstravel    dailyrate department  \
18    35        No                NaN   556.256661        NaN   
24    36        No      travel_rarely   639.785714        NaN   
30    41        No                NaN  1077.865079     Sales    
41    41        No      travel_rarely   487.087302        NaN   
57    49        No                NaN   556.256661        NaN   
...   ..       ...                ...          ...        ...   
1642  26       Yes      travel_rarely   601.301587        NaN   
1647  34       Yes         non-travel   547.238095        NaN   
1648  51       Yes  travel_frequently  1098.809524        NaN   
1653  56        No                NaN  1032.487286        NaN   
1673  43        No                NaN   488.944444        NaN   

      distancefromhome  education educationfield  employeecount  \
18                 -13          5  Life Sciences              1   
24                 -42        

In [68]:

#Errores tipográficos en algunos valores de las columnas categóricas. Por ejemplo, en la columna `MaritalStatus` en vez de "Married" en algunas filas aparece "Marreid". 

# Valores únicos en MaritalStatus
print("Valores únicos en 'maritalstatus':", df['maritalstatus'].unique())



Valores únicos en 'maritalstatus': [nan 'Married' 'Divorced' 'Single' 'divorced' 'Marreid']


In [ ]:
# Reemplazar errores tipográficos
df['maritalstatus'] = df['maritalstatus'].replace({
    "marreid": "married",
    "Marreid": "married",
    "divorcd": "divorced",
    'Divorced': "divorced"
    # Añade más reemplazos según sea necesario
})
df['maritalstatus']

0            NaN
1            NaN
2        Married
3        Married
4       divorced
5            NaN
6            NaN
7        Married
8        Married
9            NaN
10           NaN
11       Married
12       Married
13       Married
14        Single
15           NaN
16        Single
17           NaN
18       Married
19           NaN
20           NaN
21        Single
22      divorced
23       Married
24           NaN
25       Married
26       Married
27        Single
28       Married
29           NaN
30      divorced
31           NaN
32           NaN
33        Single
34        Single
35      divorced
36       Married
37       Married
38       Married
39       Married
40       Married
41        Single
42      divorced
43        Single
44      divorced
45       Married
46        Single
47       Married
48        Single
49       Married
50       Married
51           NaN
52       Married
53       Married
54      divorced
55      divorced
56           NaN
57           NaN
58       Marri

In [12]:
df['maritalstatus'] = df['maritalstatus'].str.lower()

In [13]:
df['maritalstatus'].unique()

array([nan, 'married', 'divorced', 'single'], dtype=object)

In [ ]:
#Columnas redundantes, es decir, columnas que nos dan la misma información expresada de forma diferente.

# Eliminar columnas duplicadas
df = df.loc[:, ~df.T.duplicated()]  

# Verificar resultado
print("Columnas restantes después de eliminar duplicadas:", df.columns)

Columnas restantes después de eliminar duplicadas: Index(['age', 'attrition', 'businesstravel', 'dailyrate', 'department',
       'distancefromhome', 'education', 'educationfield', 'employeecount',
       'employeenumber', 'environmentsatisfaction', 'gender', 'hourlyrate',
       'jobinvolvement', 'joblevel', 'jobrole', 'jobsatisfaction',
       'maritalstatus', 'monthlyincome', 'monthlyrate', 'numcompaniesworked',
       'over18', 'overtime', 'percentsalaryhike', 'performancerating',
       'relationshipsatisfaction', 'standardhours', 'stockoptionlevel',
       'totalworkingyears', 'trainingtimeslastyear', 'worklifebalance',
       'yearsatcompany', 'yearsincurrentrole', 'yearssincelastpromotion',
       'yearswithcurrmanager', 'datebirth', 'salary', 'roledepartament',
       'numberchildren', 'remotework'],
      dtype='object')


In [14]:
# Si tienes 'datebirth', puedes calcular 'age' así:
from datetime import datetime


In [15]:
pd.options.mode.copy_on_write = True   # Recomendamos activar la función Copiar al escribir para aprovechar las mejoras
#esto lo puse porque me lo recomendo el visial code

current_year = datetime.now().year
df['age'] = current_year - df['datebirth']
df['age']

0       52
1       53
2       43
3       48
4       47
5       49
6       60
7       43
8       42
9       42
10      42
11      57
12      39
13      42
14      56
15      41
16      59
17      47
18      36
19      41
20      46
21      34
22      37
23      48
24      37
25      36
26      53
27      37
28      34
29      35
30      42
31      48
32      54
33      36
34      35
35      47
36      44
37      37
38      61
39      41
40      33
41      42
42      54
43      37
44      47
45      39
46      52
47      44
48      38
49      33
50      39
51      47
52      36
53      44
54      57
55      37
56      39
57      50
58      40
59      41
60      37
61      38
62      36
63      34
64      51
65      49
66      45
67      45
68      41
69      35
70      36
71      51
72      50
73      39
74      34
75      48
76      39
77      38
78      31
79      59
80      35
81      59
82      39
83      30
84      56
85      42
86      40
87      39
88      44
89      32
90      51

In [76]:
#verificar que todo este correcto según lo que pide fase dos, ultimo punto solo planteado.