In [2]:
import numpy as np
import pandas as pd
pd.set_option('display.max_columns', None)  # Esto es para ver todas las columnas de un dataframe
# pd.set_option('display.max_rows', None)     # Esto es para ver todas las filas de un dataframe

In [3]:
df = pd.read_csv('../datos/hr_raw_data_final.csv', index_col=0)

df.head(20)

age attrition     businesstravel    dailyrate                department  \
0   51        No                NaN  2015.722222                       NaN   
1   52        No                NaN  2063.388889                       NaN   
2   42        No      travel_rarely  1984.253968   Research & Development    
3   47        No      travel_rarely  1771.404762                       NaN   
4   46        No                NaN  1582.771346                       NaN   
5   48        No                NaN  1771.920635   Research & Development    
6   59        No                NaN  1032.487286                       NaN   
7   42        No      travel_rarely   556.256661                       NaN   
8   41        No                NaN  1712.182540                       NaN   
9   41        No  travel_frequently  1973.984127                       NaN   
10  41        No         non-travel  2060.706349                       NaN   
11  56        No      travel_rarely  1382.746032                       NaN   
12  38        No                NaN  1362.523810                       NaN   
13  41       Yes      travel_rarely  2016.547619                       NaN   
14  55        No                NaN  1973.984127                       NaN   
15  40        No      travel_rarely  1861.373016                       NaN   
16  58       Yes      travel_rarely  1985.698413                       NaN   
17  46        No      travel_rarely  1582.771346                       NaN   
18  35        No                NaN   556.256661                       NaN   
19  40        No      travel_rarely  1032.487286                       NaN   

    distancefromhome  education    educationfield  employeecount  \
0                  6          3               NaN              1   
1                  1          4     Life Sciences              1   
2                  4          2  Technical Degree              1   
3                  2          4           Medical              1   
4                  3          3  Technical Degree              1   
5                 22          3           Medical              1   
6                 25          3     Life Sciences              1   
7                  1          1               NaN              1   
8                  2          5               NaN              1   
9                  9          3               NaN              1   
10                 7          1               NaN              1   
11                23          3     Life Sciences              1   
12                10          3           Medical              1   
13                12          3               NaN              1   
14                14          4           Medical              1   
15                 2          4               NaN              1   
16                 2          4               NaN              1   
17                 2          3               NaN              1   
18               -13          5     Life Sciences              1   
19                15          3     Life Sciences              1   

    employeenumber  environmentsatisfaction  gender  hourlyrate  \
0                1                        1       0         NaN   
1                2                        3       0         NaN   
2                3                        3       0         NaN   
3                4                        1       1         NaN   
4                5                        1       1         NaN   
5                6                        4       1         NaN   
6                7                        1       1         NaN   
7                8                        2       0   69.532083   
8                9                        2       1         NaN   
9               10                        1       0         NaN   
10              11                        2       1         NaN   
11              12                        4       0  172.843254   
12              13                        2       1         NaN 

In [89]:
df.head(1)

age attrition businesstravel    dailyrate department  distancefromhome  \
0  51        No            NaN  2015.722222        NaN                 6   

   education educationfield  employeecount  employeenumber  \
0          3            NaN              1               1   

   environmentsatisfaction  gender  hourlyrate  jobinvolvement  joblevel  \
0                        1       0         NaN               3         5   

               jobrole  jobsatisfaction maritalstatus monthlyincome  \
0   resEArch DIREcToR                 3           NaN     16280,83$   

  monthlyrate  numcompaniesworked over18 overtime  percentsalaryhike  \
0   42330,17$                   7      Y       No                 13   

  performancerating  relationshipsatisfaction standardhours  stockoptionlevel  \
0               3,0                         3     Full Time                 0   

  totalworkingyears  trainingtimeslastyear worklifebalance  yearsatcompany  \
0               NaN                      5             3,0              20   

  yearsincurrentrole  yearssincelastpromotion  yearswithcurrmanager  \
0                NaN                       15                    15   

  sameasmonthlyincome  datebirth      salary roledepartament  numberchildren  \
0           16280,83$       1972  195370,00$             NaN             NaN   

  remotework  
0        Yes

In [5]:
# Columnas y filas
print(f"El número de filas que tenemos es {df.shape[0]}, y el número de columnas es {df.shape[1]}")

El número de filas que tenemos es 1678, y el número de columnas es 41


In [6]:
# Tamaño del Dataframe
df.size

68798

In [7]:
#utilizamos el metodo '.describe()' para sacar los principales estadísticos del DataFrame
# por defecto, nos devolverá solo los estadísticos de las VARIABLES NUMÉRICAS

df.describe()

dailyrate  distancefromhome    education  employeecount  \
count  1678.000000       1678.000000  1678.000000         1678.0   
mean    668.079714          4.504172     2.932658            1.0   
std     470.787298         14.652066     1.024270            0.0   
min     104.103175        -49.000000     1.000000            1.0   
25%     290.035510          2.000000     2.000000            1.0   
50%     556.256661          5.000000     3.000000            1.0   
75%     971.956349         11.000000     4.000000            1.0   
max    2063.388889         29.000000     5.000000            1.0   

       employeenumber  environmentsatisfaction       gender  hourlyrate  \
count     1678.000000              1678.000000  1678.000000  411.000000   
mean       809.859952                 4.264005     0.398689   83.140768   
std        467.084867                 6.912695     0.489774   57.272101   
min          1.000000                 1.000000     0.000000   13.012897   
25%        403.250000                 2.000000     0.000000   36.254439   
50%        813.500000                 3.000000     0.000000   69.532083   
75%       1215.750000                 4.000000     1.000000  116.987103   
max       1614.000000                49.000000     1.000000  255.963294   

       jobinvolvement     joblevel  jobsatisfaction  numcompaniesworked  \
count     1678.000000  1678.000000      1678.000000         1678.000000   
mean         2.740763     2.064362         2.743147            2.670441   
std          0.710359     1.099425         1.105172            2.501133   
min          1.000000     1.000000         1.000000            0.000000   
25%          2.000000     1.000000         2.000000            1.000000   
50%          3.000000     2.000000         3.000000            2.000000   
75%          3.000000     3.000000         4.000000            4.000000   
max          4.000000     5.000000         4.000000            9.000000   

       percentsalaryhike  relationshipsatisfaction  stockoptionlevel  \
count        1678.000000               1678.000000       1678.000000   
mean           15.154350                  2.700238          0.787843   
std             3.649607                  1.079494          0.843252   
min            11.000000                  1.000000          0.000000   
25%            12.000000                  2.000000          0.000000   
50%            14.000000                  3.000000          1.000000   
75%            18.000000                  4.000000          1.000000   
max            25.000000                  4.000000          3.000000   

       trainingtimeslastyear  yearsatcompany  yearssincelastpromotion  \
count            1678.000000     1678.000000              1678.000000   
mean                2.795590        7.124553                 2.241955   
std                 1.288657        6.173837                 3.246554   
min                 0.000000        0.000000                 0.000000   
25%                 2.000000        3.000000                 0.000000   
50%                 3.000000        5.000000                 1.000000   
75%                 3.000000        9.000000                 3.000000   
max                 6.000000       40.000000                15.000000   

       yearswithcurrmanager    datebirth  numberchildren  
count           1678.000000  1678.000000             0.0  
mean               4.200238  1986.047080             NaN  
std                3.554224     9.154908             NaN  
min                0.000000  1963.000000             NaN  
25%                2.000000  1980.000000             NaN  
50%                3.000000  1987.000000             NaN  
75%                7.000000  1993.000000             NaN  
max               17.000000  2005.000000             NaN

In [8]:
# podemos usar el método '.T' para transponer los resultados
df.describe().T

count         mean         std          min  \
dailyrate                 1678.0   668.079714  470.787298   104.103175   
distancefromhome          1678.0     4.504172   14.652066   -49.000000   
education                 1678.0     2.932658    1.024270     1.000000   
employeecount             1678.0     1.000000    0.000000     1.000000   
employeenumber            1678.0   809.859952  467.084867     1.000000   
environmentsatisfaction   1678.0     4.264005    6.912695     1.000000   
gender                    1678.0     0.398689    0.489774     0.000000   
hourlyrate                 411.0    83.140768   57.272101    13.012897   
jobinvolvement            1678.0     2.740763    0.710359     1.000000   
joblevel                  1678.0     2.064362    1.099425     1.000000   
jobsatisfaction           1678.0     2.743147    1.105172     1.000000   
numcompaniesworked        1678.0     2.670441    2.501133     0.000000   
percentsalaryhike         1678.0    15.154350    3.649607    11.000000   
relationshipsatisfaction  1678.0     2.700238    1.079494     1.000000   
stockoptionlevel          1678.0     0.787843    0.843252     0.000000   
trainingtimeslastyear     1678.0     2.795590    1.288657     0.000000   
yearsatcompany            1678.0     7.124553    6.173837     0.000000   
yearssincelastpromotion   1678.0     2.241955    3.246554     0.000000   
yearswithcurrmanager      1678.0     4.200238    3.554224     0.000000   
datebirth                 1678.0  1986.047080    9.154908  1963.000000   
numberchildren               0.0          NaN         NaN          NaN   

                                  25%          50%          75%          max  
dailyrate                  290.035510   556.256661   971.956349  2063.388889  
distancefromhome             2.000000     5.000000    11.000000    29.000000  
education                    2.000000     3.000000     4.000000     5.000000  
employeecount                1.000000     1.000000     1.000000     1.000000  
employeenumber             403.250000   813.500000  1215.750000  1614.000000  
environmentsatisfaction      2.000000     3.000000     4.000000    49.000000  
gender                       0.000000     0.000000     1.000000     1.000000  
hourlyrate                  36.254439    69.532083   116.987103   255.963294  
jobinvolvement               2.000000     3.000000     3.000000     4.000000  
joblevel                     1.000000     2.000000     3.000000     5.000000  
jobsatisfaction              2.000000     3.000000     4.000000     4.000000  
numcompaniesworked           1.000000     2.000000     4.000000     9.000000  
percentsalaryhike           12.000000    14.000000    18.000000    25.000000  
relationshipsatisfaction     2.000000     3.000000     4.000000     4.000000  
stockoptionlevel             0.000000     1.000000     1.000000     3.000000  
trainingtimeslastyear        2.000000     3.000000     3.000000     6.000000  
yearsatcompany               3.000000     5.000000     9.000000    40.000000  
yearssincelastpromotion      0.000000     1.000000     3.000000    15.000000  
yearswithcurrmanager         2.000000     3.000000     7.000000    17.000000  
datebirth                 1980.000000  1987.000000  1993.000000  2005.000000  
numberchildren                    NaN          NaN          NaN          NaN

In [9]:
# hagamos lo mismo para las columnas categóricas, para eso tendremos que incluir entre los paréntesis el parámetro include = "object"
df.describe(include = "object").T

count unique  \
age                  1678     54   
attrition            1678      2   
businesstravel        877      3   
department            312      3   
educationfield        904      6   
jobrole              1678   1579   
maritalstatus        1003      5   
monthlyincome        1189    493   
monthlyrate          1678    673   
over18                740      1   
overtime              982      2   
performancerating    1478      2   
standardhours        1327      2   
totalworkingyears    1129     40   
worklifebalance      1564      4   
yearsincurrentrole     35     10   
sameasmonthlyincome  1189    493   
salary               1393    583   
roledepartament       312    301   
remotework           1678      5   

                                                                 top  freq  
age                                                               35    88  
attrition                                                         No  1406  
businesstravel                                         travel_rarely   616  
department                                   Research & Development    203  
educationfield                                         Life Sciences   367  
jobrole                                                     mANager      5  
maritalstatus                                                Married   419  
monthlyincome                                               2342,59$   228  
monthlyrate                                                11681,39$   326  
over18                                                             Y   740  
overtime                                                          No   714  
performancerating                                                3,0  1257  
standardhours                                              Part Time   927  
totalworkingyears                                               10,0   151  
worklifebalance                                                  3,0   946  
yearsincurrentrole                                               2,0    12  
sameasmonthlyincome                                         2342,59$   228  
salary                                                     53914,11$   270  
roledepartament       rESEArcH SCiEntIst  -  Research & Development      2  
remotework                                                         1   375

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1678 entries, 0 to 1677
Data columns (total 41 columns):
 #   Column                    Non-Null Count  Dtype  
---  ------                    --------------  -----  
 0   age                       1678 non-null   object 
 1   attrition                 1678 non-null   object 
 2   businesstravel            877 non-null    object 
 3   dailyrate                 1678 non-null   float64
 4   department                312 non-null    object 
 5   distancefromhome          1678 non-null   int64  
 6   education                 1678 non-null   int64  
 7   educationfield            904 non-null    object 
 8   employeecount             1678 non-null   int64  
 9   employeenumber            1678 non-null   int64  
 10  environmentsatisfaction   1678 non-null   int64  
 11  gender                    1678 non-null   int64  
 12  hourlyrate                411 non-null    float64
 13  jobinvolvement            1678 non-null   int64  
 14  joblevel     

In [11]:
# Todas las columnas
df.columns

Index(['age', 'attrition', 'businesstravel', 'dailyrate', 'department',
       'distancefromhome', 'education', 'educationfield', 'employeecount',
       'employeenumber', 'environmentsatisfaction', 'gender', 'hourlyrate',
       'jobinvolvement', 'joblevel', 'jobrole', 'jobsatisfaction',
       'maritalstatus', 'monthlyincome', 'monthlyrate', 'numcompaniesworked',
       'over18', 'overtime', 'percentsalaryhike', 'performancerating',
       'relationshipsatisfaction', 'standardhours', 'stockoptionlevel',
       'totalworkingyears', 'trainingtimeslastyear', 'worklifebalance',
       'yearsatcompany', 'yearsincurrentrole', 'yearssincelastpromotion',
       'yearswithcurrmanager', 'sameasmonthlyincome', 'datebirth', 'salary',
       'roledepartament', 'numberchildren', 'remotework'],
      dtype='object')

In [12]:
# Tipos de datos de cada columna

df.dtypes

age                          object
attrition                    object
businesstravel               object
dailyrate                   float64
department                   object
distancefromhome              int64
education                     int64
educationfield               object
employeecount                 int64
employeenumber                int64
environmentsatisfaction       int64
gender                        int64
hourlyrate                  float64
jobinvolvement                int64
joblevel                      int64
jobrole                      object
jobsatisfaction               int64
maritalstatus                object
monthlyincome                object
monthlyrate                  object
numcompaniesworked            int64
over18                       object
overtime                     object
percentsalaryhike             int64
performancerating            object
relationshipsatisfaction      int64
standardhours                object
stockoptionlevel            

In [13]:
# sacamos las columnas que son de tipo object (categóricas) de nuestro DataFrame usando el método '.select_dtypes()'
df_cat = df.select_dtypes(include = "object")
df_cat.head()

age attrition businesstravel                department    educationfield  \
0  51        No            NaN                       NaN               NaN   
1  52        No            NaN                       NaN     Life Sciences   
2  42        No  travel_rarely   Research & Development   Technical Degree   
3  47        No  travel_rarely                       NaN           Medical   
4  46        No            NaN                       NaN  Technical Degree   

               jobrole maritalstatus monthlyincome monthlyrate over18  \
0   resEArch DIREcToR            NaN     16280,83$   42330,17$      Y   
1             ManAGeR            NaN           NaN   43331,17$    NaN   
2             ManaGER        Married           NaN   41669,33$    NaN   
3   ReseArCH DIrECtOr        Married     14307,50$   37199,50$      Y   
4     sAleS EXECUtIve       Divorced     12783,92$   33238,20$      Y   

  overtime performancerating standardhours totalworkingyears worklifebalance  \
0       No               3,0     Full Time               NaN             3,0   
1      NaN               3,0           NaN              34,0             3,0   
2       No               3,0           NaN              22,0             NaN   
3      NaN               3,0     Full Time               NaN             NaN   
4       No               3,0           NaN               NaN             3,0   

  yearsincurrentrole sameasmonthlyincome      salary  \
0                NaN           16280,83$  195370,00$   
1                NaN                 NaN  199990,00$   
2                NaN                 NaN  192320,00$   
3                NaN           14307,50$  171690,00$   
4                NaN           12783,92$         NaN   

                        roledepartament remotework  
0                                   NaN        Yes  
1                                   NaN          1  
2   ManaGER  -  Research & Development           1  
3                                   NaN      False  
4                                   NaN          0

In [14]:
# inplace = True porque queremos que los cambios realizados se sobreescriban en el DataFrame
df_cat.drop(['monthlyincome', 'monthlyrate', 'performancerating', 'totalworkingyears' , 'worklifebalance', 'sameasmonthlyincome', 'salary', 'age'], axis = 1, inplace=True)
# chuequeamos como se ha quedado el DataFrame y vemos que ya lo tenemos preparado para poder evaluar cuales son sus valores únicos ('.unique()') y sus frecuencias ('.value_counts()')
df_cat.head()

attrition businesstravel                department    educationfield  \
0        No            NaN                       NaN               NaN   
1        No            NaN                       NaN     Life Sciences   
2        No  travel_rarely   Research & Development   Technical Degree   
3        No  travel_rarely                       NaN           Medical   
4        No            NaN                       NaN  Technical Degree   

               jobrole maritalstatus over18 overtime standardhours  \
0   resEArch DIREcToR            NaN      Y       No     Full Time   
1             ManAGeR            NaN    NaN      NaN           NaN   
2             ManaGER        Married    NaN       No           NaN   
3   ReseArCH DIrECtOr        Married      Y      NaN     Full Time   
4     sAleS EXECUtIve       Divorced      Y       No           NaN   

  yearsincurrentrole                       roledepartament remotework  
0                NaN                                   NaN        Yes  
1                NaN                                   NaN          1  
2                NaN   ManaGER  -  Research & Development           1  
3                NaN                                   NaN      False  
4                NaN                                   NaN          0

In [15]:
# creamos una variable con los nombres de las columnas del DataFrame de las variables categóricas utilizando el método '.columns'
columnas_cat = df_cat.columns
print(f"Las columnas del DataFrame de variables categóricas son {columnas_cat}")

# empezamos a iterar por cada una de las columnas para sacar sus valores únicos y sus frecuencias
for columna in columnas_cat:
    print(f" \n----------- ESTAMOS ANALIZANDO LA COLUMNA: '{columna.upper()}' -----------\n")
    print(f"Sus valores únicos son: {df_cat[columna].unique()}\n")
    print(f"Las frecuencias de los valores únicos de las categorías son: {df_cat[columna].value_counts()} ")
    print(f"Cantidad de valores nulos: {df_cat[columna].isna().sum()}")

Las columnas del DataFrame de variables categóricas son Index(['attrition', 'businesstravel', 'department', 'educationfield',
       'jobrole', 'maritalstatus', 'over18', 'overtime', 'standardhours',
       'yearsincurrentrole', 'roledepartament', 'remotework'],
      dtype='object')
 
----------- ESTAMOS ANALIZANDO LA COLUMNA: 'ATTRITION' -----------

Sus valores únicos son: ['No' 'Yes']

Las frecuencias de los valores únicos de las categorías son: attrition
No     1406
Yes     272
Name: count, dtype: int64 
Cantidad de valores nulos: 0
 
----------- ESTAMOS ANALIZANDO LA COLUMNA: 'BUSINESSTRAVEL' -----------

Sus valores únicos son: [nan 'travel_rarely' 'travel_frequently' 'non-travel']

Las frecuencias de los valores únicos de las categorías son: businesstravel
travel_rarely        616
travel_frequently    168
non-travel            93
Name: count, dtype: int64 
Cantidad de valores nulos: 801
 
----------- ESTAMOS ANALIZANDO LA COLUMNA: 'DEPARTMENT' -----------

Sus valores únicos so

In [16]:
# Porcentaje de nulos de cada columna

df.isna().sum()/df.shape[0]*100

age                           0.000000
attrition                     0.000000
businesstravel               47.735399
dailyrate                     0.000000
department                   81.406436
distancefromhome              0.000000
education                     0.000000
educationfield               46.126341
employeecount                 0.000000
employeenumber                0.000000
environmentsatisfaction       0.000000
gender                        0.000000
hourlyrate                   75.506555
jobinvolvement                0.000000
joblevel                      0.000000
jobrole                       0.000000
jobsatisfaction               0.000000
maritalstatus                40.226460
monthlyincome                29.141836
monthlyrate                   0.000000
numcompaniesworked            0.000000
over18                       55.899881
overtime                     41.477950
percentsalaryhike             0.000000
performancerating            11.918951
relationshipsatisfaction 

In [17]:
# Porcentaje de nulos sobre los nulos

# Cantidad de nulos que hay por columnas
nulos_columnas = df.isna().sum()

# El total de nulos en todas las columnas
total_nulos = nulos_columnas.sum()

porcentaje = ((nulos_columnas/total_nulos) *100).round(2)

print(f' El porcetaje que cada columna tiene de nulo es de: \n {porcentaje}')

 El porcetaje que cada columna tiene de nulo es de: 
 age                          0.00
attrition                    0.00
businesstravel               5.85
dailyrate                    0.00
department                   9.98
distancefromhome             0.00
education                    0.00
educationfield               5.66
employeecount                0.00
employeenumber               0.00
environmentsatisfaction      0.00
gender                       0.00
hourlyrate                   9.26
jobinvolvement               0.00
joblevel                     0.00
jobrole                      0.00
jobsatisfaction              0.00
maritalstatus                4.93
monthlyincome                3.57
monthlyrate                  0.00
numcompaniesworked           0.00
over18                       6.86
overtime                     5.09
percentsalaryhike            0.00
performancerating            1.46
relationshipsatisfaction     0.00
standardhours                2.57
stockoptionlevel            

In [18]:
# Código nos esta diciendo que no tenemos filas duplicadas
df.duplicated().sum()

64

In [19]:
# si por ejemplo evaluaramos si existen valores duplicados para la columna de 'id_' debería salir que no existe ningún valor duplicado, ya que estos id deberían ser únicos
# usemos de nuevo el parámetro 'subset'
df.duplicated(subset  = "employeenumber").sum() 

64

In [20]:
dupli = df[df.duplicated(subset  = "employeenumber", keep=False)].sort_values('employeenumber')

In [21]:
dupli 

age attrition businesstravel    dailyrate department  distancefromhome  \
8     41        No            NaN  1712.182540        NaN                 2   
1656  41        No            NaN  1712.182540        NaN                 2   
60    36        No            NaN   610.174603        NaN                 5   
1652  36        No            NaN   610.174603        NaN                 5   
1676  47        No  travel_rarely  1032.487286        NaN                 4   
...   ..       ...            ...          ...        ...               ...   
1638  48        No  travel_rarely   417.960317        NaN                 2   
1657  45        No  travel_rarely   495.753968        NaN                 2   
1568  45        No  travel_rarely   495.753968        NaN                 2   
1671  31        No            NaN   556.256661        NaN                12   
1607  31        No            NaN   556.256661        NaN                12   

      education educationfield  employeecount  employeenumber  \
8             5            NaN              1               9   
1656          5            NaN              1               9   
60            2            NaN              1              61   
1652          2            NaN              1              61   
1676          3  Life Sciences              1              76   
...         ...            ...            ...             ...   
1638          5            NaN              1            1568   
1657          3          Other              1            1569   
1568          3          Other              1            1569   
1671          3        Medical              1            1608   
1607          3        Medical              1            1608   

      environmentsatisfaction  gender  hourlyrate  jobinvolvement  joblevel  \
8                           2       1         NaN               3         4   
1656                        2       1         NaN               3         4   
60                          4       0         NaN               3         2   
1652                        4       0         NaN               3         2   
1676                        3       1         NaN               2         3   
...                       ...     ...         ...             ...       ...   
1638                        2       1         NaN               3         2   
1657                        4       0         NaN               3         2   
1568                        4       0         NaN               3         2   
1671                        4       1         NaN               3         2   
1607                        4       1         NaN               3         2   

                          jobrole  jobsatisfaction maritalstatus  \
8                        mANAGEr                 1       Married   
1656                     mANAGEr                 1       Married   
60         lAboratORy TeChNiCiaN                 2        Single   
1652       lAboratORy TeChNiCiaN                 2        Single   
1676      maNufACTURING DIREctOr                 2      Divorced   
...                           ...              ...           ...   
1638             sALES EXEcuTIVe                 4       Married   
1657             sAles executiVe                 2           NaN   
1568             sAles executiVe                 2           NaN   
1671   HEaltHCarE REPreSENtAtIve                 4           NaN   
1607   HEaltHCarE REPreSENtAtIve                 4           NaN   

     monthlyincome monthlyrate  numcompaniesworked over18 overtime  \
8        13829,17$   35955,83$                   7    NaN       No   
1656     13829,17$   35955,83$                   7    NaN       No   
60        4928,33$   12813,67$                   8      Y       No   
1652      4928,33$   12813,67$                   8      Y       No   
1676      8339,32$   21682,23$                   8    NaN      Yes   
...            ...         ...                 ...    ...      ...   
1638      3375,83$ 

In [22]:
df['gender'].unique()
df['gender'].value_counts()

gender
0    1009
1     669
Name: count, dtype: int64

In [23]:
df['environmentsatisfaction'].unique()

array([ 1,  3,  4,  2, 42, 37, 35, 25, 27, 31, 39, 21, 15, 14, 33, 19, 12,
       13, 28, 47, 36, 29, 24, 46, 16, 22, 41, 49, 11, 48, 18, 10, 45, 38,
       17, 20, 26, 43])

In [24]:
df['environmentsatisfaction'].value_counts()

environmentsatisfaction
4     483
3     471
2     316
1     306
35      7
12      7
14      6
13      6
24      5
47      5
36      4
48      4
41      4
46      4
42      4
45      3
11      3
22      3
17      3
18      3
20      3
25      3
27      3
37      2
29      2
19      2
38      2
31      2
15      2
16      2
26      1
39      1
10      1
49      1
21      1
28      1
33      1
43      1
Name: count, dtype: int64

In [25]:
df['employeenumber'].unique()

array([   1,    2,    3, ..., 1612, 1613, 1614])

In [26]:
df['employeecount'].unique()

array([1])

In [27]:
df['educationfield'].unique()

array([nan, 'Life Sciences', 'Technical Degree', 'Medical', 'Other',
       'Marketing', 'Human Resources'], dtype=object)

In [28]:
# Valores unicos de la columna 'AGE'

df['age'].unique()

array(['51', '52', '42', '47', '46', '48', '59', '41', '56', '38', '55',
       '40', '58', '35', '45', '33', '36', '34', 'forty-seven', '53',
       '43', '60', '32', '37', '49', '39', '50', '44', '30',
       'fifty-eight', '29', '31', '54', '57', '27', 'thirty-six', '28',
       '26', 'fifty-five', '25', 'fifty-two', 'thirty-one', '24',
       'thirty', '23', '22', '21', '20', 'twenty-six', '19',
       'thirty-seven', '18', 'thirty-two', 'twenty-four'], dtype=object)

In [29]:

df['attrition'].unique()

array(['No', 'Yes'], dtype=object)

In [30]:
df['businesstravel'].unique()

array([nan, 'travel_rarely', 'travel_frequently', 'non-travel'],
      dtype=object)

In [31]:
df['businesstravel'].value_counts(dropna=False)

businesstravel
NaN                  801
travel_rarely        616
travel_frequently    168
non-travel            93
Name: count, dtype: int64

In [32]:
df['dailyrate'].value_counts()

dailyrate
556.256661     326
290.035510     308
1032.487286    150
1582.771346     55
1973.984127     38
              ... 
320.047619       1
470.063492       1
436.428571       1
501.325397       1
2004.785714      1
Name: count, Length: 673, dtype: int64

In [33]:
df['department'].unique()

array([nan, ' Research & Development ', ' Sales ', ' Human Resources '],
      dtype=object)

In [34]:
df['distancefromhome'].unique()

array([  6,   1,   4,   2,   3,  22,  25,   9,   7,  23,  10,  12,  14,
       -13,  15,   8, -42,  28, -37,   5,  16, -35,  26, -26,  24,  29,
       -25,  17,  21, -18, -10, -30, -27,  20, -31, -29, -39,  18, -21,
       -15,  11,  13, -14,  19, -33, -34, -46, -36, -19,  27, -12, -23,
       -45, -28, -47, -32, -24, -16, -22, -41, -49, -11, -48, -38, -20,
       -17, -43, -40, -44])

In [35]:
df['education'].unique()

array([3, 4, 2, 1, 5])

In [36]:
df['education'].value_counts()

education
3    649
4    461
2    322
1    186
5     60
Name: count, dtype: int64

In [37]:
df['educationfield'].value_counts(dropna=False)

educationfield
NaN                 774
Life Sciences       367
Medical             286
Marketing           106
Technical Degree     70
Other                63
Human Resources      12
Name: count, dtype: int64

In [38]:
df['hourlyrate'].unique()

array([         nan,  69.53208262, 172.84325397, 216.04761905,
        79.97321429, 129.06091077, 246.74801587, 207.17460317,
        60.8859127 ,  36.25443872, 139.99503968,  86.24107143,
       197.84641831,  61.06646825, 245.62003968, 123.97718254,
       148.44246032, 255.96329365, 134.41071429,  71.92559524,
       113.78869048, 175.10019841, 247.49007937, 220.83234127,
        91.34821429,  37.77480159, 198.9593254 , 124.05456349,
       247.58035714, 108.48809524,  43.17857143,  68.46924603,
        32.48710317,  55.26289683,  83.46825397,  79.26388889,
        72.28670635,  45.96428571,  31.66170635,  65.19345238,
        52.24503968, 143.9156746 , 113.40178571, 143.19345238,
       139.86607143,  70.57142857,  97.04861111,  45.02281746,
       223.47619048, 134.9781746 ,  74.40178571,  67.14087302,
        58.06150794,  35.05357143,  73.18948413, 164.33134921,
        43.53968254,  54.79861111, 252.59722222,  83.81646825,
        46.71230159,  33.00297619,  70.77777778,  69.23

In [39]:
df['hourlyrate'].value_counts()

hourlyrate
36.254439     76
69.532083     75
129.060911    41
197.846418    14
246.748016     8
              ..
28.205357      1
54.914683      1
227.487103     1
78.180556      1
133.159722     1
Name: count, Length: 194, dtype: int64

In [40]:
df['jobinvolvement'].unique()

array([3, 2, 4, 1])

In [41]:
df['jobinvolvement'].value_counts(dropna=False)

jobinvolvement
3    995
2    421
4    170
1     92
Name: count, dtype: int64

In [42]:
df['joblevel'].unique()

array([5, 4, 3, 2, 1])

In [43]:
df['joblevel'].value_counts(dropna=False)

joblevel
2    618
1    612
3    255
4    114
5     79
Name: count, dtype: int64

In [44]:
df['jobsatisfaction'].unique()

array([3, 4, 1, 2])

In [45]:
df['numcompaniesworked'].unique()

array([7, 0, 1, 3, 2, 4, 8, 9, 5, 6])

In [46]:
df['numcompaniesworked'].value_counts(dropna=False)

numcompaniesworked
1    597
0    234
3    174
4    166
2    163
7     88
6     75
5     67
9     59
8     55
Name: count, dtype: int64

In [47]:
df['over18'].unique()

array(['Y', nan], dtype=object)

In [48]:
df['over18'].value_counts(dropna=False)

over18
NaN    938
Y      740
Name: count, dtype: int64

In [49]:
df['overtime'].unique()

array(['No', nan, 'Yes'], dtype=object)

In [50]:
df['overtime'].value_counts(dropna=False)

overtime
No     714
NaN    696
Yes    268
Name: count, dtype: int64

In [51]:
df['percentsalaryhike'].unique()

array([13, 14, 11, 19, 12, 25, 16, 17, 22, 23, 20, 15, 21, 24, 18])

In [52]:
df['percentsalaryhike'].value_counts(dropna=False)

percentsalaryhike
11    241
13    239
12    238
14    229
15    112
18    102
17     92
16     89
19     86
22     61
20     60
21     51
23     33
24     26
25     19
Name: count, dtype: int64

In [53]:
df['performancerating'].unique()

array(['3,0', '4,0', nan], dtype=object)

In [54]:
df['performancerating'].value_counts(dropna=False)

performancerating
3,0    1257
4,0     221
NaN     200
Name: count, dtype: int64

In [55]:
df['relationshipsatisfaction'].unique()

array([3, 1, 4, 2])

In [56]:
df['relationshipsatisfaction'].value_counts(dropna=False)

relationshipsatisfaction
3    527
4    483
2    350
1    318
Name: count, dtype: int64

In [57]:
df['standardhours'].unique()

array(['Full Time', nan, 'Part Time'], dtype=object)

In [58]:
df['standardhours'].value_counts(dropna=False)

standardhours
Part Time    927
Full Time    400
NaN          351
Name: count, dtype: int64

In [59]:
df['stockoptionlevel'].unique()

array([0, 1, 2, 3])

In [60]:
df['stockoptionlevel'].value_counts(dropna=False)

stockoptionlevel
0    719
1    689
2    177
3     93
Name: count, dtype: int64

In [61]:
df['totalworkingyears'].unique()

array([nan, '34,0', '22,0', '28,0', '20,0', '21,0', '33,0', '40,0',
       '18,0', '25,0', '15,0', '17,0', '26,0', '16,0', '24,0', '14,0',
       '23,0', '27,0', '19,0', '11,0', '38,0', '37,0', '13,0', '12,0',
       '29,0', '10,0', '36,0', '35,0', '9,0', '31,0', '32,0', '8,0',
       '7,0', '30,0', '6,0', '5,0', '4,0', '3,0', '2,0', '1,0', '0,0'],
      dtype=object)

In [62]:
df['totalworkingyears'].value_counts(dropna=False).sort_index()

totalworkingyears
0,0       8
1,0      55
10,0    151
11,0     31
12,0     34
13,0     31
14,0     31
15,0     28
16,0     30
17,0     23
18,0     28
19,0     17
2,0      21
20,0     30
21,0     23
22,0     19
23,0     13
24,0     14
25,0      6
26,0      8
27,0      6
28,0     14
29,0      6
3,0      34
30,0      3
31,0      4
32,0      3
33,0      6
34,0      2
35,0      3
36,0      6
37,0      7
38,0      1
4,0      57
40,0      4
5,0      68
6,0      88
7,0      59
8,0      86
9,0      71
NaN     549
Name: count, dtype: int64

In [63]:
df['trainingtimeslastyear'].unique()

array([5, 3, 2, 0, 1, 4, 6])

In [64]:
df['trainingtimeslastyear'].value_counts(dropna=False)

trainingtimeslastyear
2    625
3    557
4    143
5    137
1     81
6     72
0     63
Name: count, dtype: int64

In [65]:
df['worklifebalance'].unique()

array(['3,0', nan, '2,0', '4,0', '1,0'], dtype=object)

In [66]:
df['worklifebalance'].value_counts(dropna=False)

worklifebalance
3,0    946
2,0    374
4,0    162
NaN    114
1,0     82
Name: count, dtype: int64

In [67]:
df['yearsatcompany'].unique()

array([20, 33, 22, 19, 21, 18, 24, 31, 26, 16, 23, 15, 17, 32, 14, 13, 25,
       12, 11, 37, 40, 36, 27, 29, 10,  9, 30,  8,  7, 34,  6,  5,  4,  2,
        3,  1,  0])

In [68]:
df['yearsatcompany'].value_counts(dropna=False)

yearsatcompany
5     214
1     181
3     149
2     145
10    139
4     116
7     115
8     113
9      98
6      84
0      47
11     37
20     30
13     27
15     22
14     19
22     18
18     16
12     15
16     14
21     14
19     12
17      9
24      7
25      5
33      5
26      4
36      4
32      3
27      3
31      3
40      3
29      2
23      2
34      1
37      1
30      1
Name: count, dtype: int64

In [69]:
df['yearsincurrentrole'].unique()

array([nan, '13,0', '12,0', '11,0', '7,0', '6,0', '4,0', '3,0', '2,0',
       '1,0', '0,0'], dtype=object)

In [70]:
df['yearsincurrentrole'].value_counts(dropna=False)

yearsincurrentrole
NaN     1643
2,0       12
7,0        5
0,0        4
4,0        3
1,0        3
11,0       2
6,0        2
3,0        2
13,0       1
12,0       1
Name: count, dtype: int64

In [71]:
df['yearssincelastpromotion'].unique()

array([15, 11,  5,  2,  4,  7,  0,  1, 13, 14,  8, 12,  3,  6, 10,  9])

In [72]:
df['yearswithcurrmanager'].unique()

array([15,  9,  6,  8,  7, 11, 10, 12,  4,  0,  5, 17,  2, 14,  1, 13,  3,
       16])

In [73]:
df['sameasmonthlyincome'].unique()

array(['16280,83$', nan, '14307,50$', '12783,92$', '14311,67$',
       '8339,32$', '13829,17$', '15943,72$', '16644,17$', '15034,17$',
       '16038,33$', '4492,84$', '8956,67$', '5167,50$', '3334,17$',
       '8705,83$', '2675,00$', '8555,00$', '8729,17$', '3934,17$',
       '3845,83$', '14132,50$', '8588,33$', '4505,00$', '4918,33$',
       '4928,33$', '5538,33$', '11100,00$', '5572,50$', '11560,00$',
       '15870,83$', '13345,83$', '8010,83$', '3588,33$', '14205,00$',
       '4222,50$', '3076,67$', '2342,59$', '4789,17$', '8685,00$',
       '5289,17$', '1956,67$', '10408,33$', '6683,33$', '7452,50$',
       '16060,00$', '4647,50$', '2242,50$', '6169,17$', '7352,50$',
       '2982,50$', '14815,83$', '15177,50$', '15991,67$', '15989,17$',
       '8340,00$', '6656,67$', '5902,50$', '3935,83$', '2839,17$',
       '2440,83$', '10025,83$', '12855,83$', '5135,00$', '4271,67$',
       '8015,83$', '4175,00$', '15860,83$', '8666,67$', '2327,50$',
       '4728,33$', '7010,00$', '2790,00$', '4

In [74]:
df['sameasmonthlyincome'].value_counts(dropna=False)

sameasmonthlyincome
NaN          489
2342,59$     228
4492,84$     227
8339,32$     105
12783,92$     42
            ... 
3018,33$       1
5330,83$       1
4994,17$       1
3806,67$       1
3705,83$       1
Name: count, Length: 494, dtype: int64

In [75]:
df['datebirth'].unique()

array([1972, 1971, 1981, 1976, 1977, 1975, 1964, 1982, 1967, 1985, 1968,
       1983, 1965, 1988, 1978, 1990, 1987, 1989, 1970, 1980, 1963, 1991,
       1986, 1974, 1984, 1973, 1979, 1993, 1994, 1992, 1969, 1966, 1996,
       1995, 1997, 1998, 1999, 2000, 2001, 2002, 2003, 2004, 2005])

In [76]:
df['datebirth'].value_counts(dropna=False)

datebirth
1992    89
1988    88
1989    86
1994    82
1987    80
1991    67
1993    66
1985    64
1990    63
1983    60
1986    56
1995    54
1996    54
1978    50
1981    50
1982    48
1997    47
1984    46
1980    42
1977    38
1979    34
1973    34
1999    31
1976    31
1998    28
1974    26
1968    26
1972    22
1975    22
1969    20
1970    20
1971    19
1967    18
1965    17
2001    17
2002    17
2000    15
1964    11
2003    11
2004     9
2005     9
1966     6
1963     5
Name: count, dtype: int64

In [77]:
df['salary'].unique()

array(['195370,00$', '199990,00$', '192320,00$', '171690,00$', nan,
       '100071,84$', '53914,11$', '165950,00$', '199730,00$',
       '134020,00$', '132060,00$', '195450,00$', '180410,00$',
       '192460,00$', '107480,00$', '167520,00$', '62010,00$',
       '198450,00$', '40010,00$', '104470,00$', '191324,62$',
       '160640,00$', '32100,00$', '102660,00$', '104750,00$', '61620,00$',
       '47210,00$', '153407,07$', '28111,13$', '46150,00$', '169590,00$',
       '54060,00$', '59020,00$', '108550,00$', '59140,00$', '66460,00$',
       '139730,00$', '66870,00$', '47350,00$', '138720,00$', '190450,00$',
       '96130,00$', '115100,00$', '170460,00$', '36920,00$', '198470,00$',
       '23080,00$', '57470,00$', '104220,00$', '63470,00$', '23480,00$',
       '30720,00$', '124900,00$', '80200,00$', '170680,00$', '89430,00$',
       '192720,00$', '55770,00$', '26910,00$', '74030,00$', '88230,00$',
       '35790,00$', '177790,00$', '182130,00$', '135770,00$',
       '191900,00$', '171230,

In [78]:
df['roledepartament'].unique()

array([nan, ' ManaGER  -  Research & Development ',
       ' MANAger  -  Research & Development ',
       ' heaLtHcArE repResENtATiVe  -  Research & Development ',
       ' saLEs exEcutIVe  -  Sales ', ' Sales ExECuTIVe  -  Sales ',
       ' heALthCArE RePResEntaTIVe  -  Research & Development ',
       ' lABORAtOry tECHnIcIan  -  Research & Development ',
       ' ManufactUrINg DiReCTOr  -  Research & Development ',
       ' SaleS eXEcUtIVE  -  Sales ',
       ' HEaLthcaRe rEprEsEnTAtiVe  -  Research & Development ',
       ' rESeArCH sCientIST  -  Research & Development ',
       ' healTHCAre rePREseNtATiVE  -  Research & Development ',
       ' mANaGer  -  Research & Development ',
       ' HEAltHCaRe REPreseNTatIve  -  Research & Development ',
       ' SaLeS eXECUTivE  -  Sales ',
       ' reSeARCH SCIEnTiST  -  Research & Development ',
       ' ReSearch DiRecTOR  -  Research & Development ',
       ' resEaRCh SciEnTist  -  Research & Development ',
       ' hUmaN REsoUrCes  -  H

In [79]:
df['numberchildren'].unique()

array([nan])

In [80]:
df['remotework'].unique()

array(['Yes', '1', 'False', '0', 'True'], dtype=object)

In [81]:
df['remotework'].value_counts(dropna=False)

remotework
1        375
True     362
False    318
0        318
Yes      305
Name: count, dtype: int64

In [82]:
df['maritalstatus'].value_counts(dropna=False)

maritalstatus
NaN         675
Married     419
Single      343
Divorced    194
Marreid      36
divorced     11
Name: count, dtype: int64

In [83]:
df['maritalstatus'].unique()

array([nan, 'Married', 'Divorced', 'Single', 'divorced', 'Marreid'],
      dtype=object)

In [84]:
df['monthlyincome'].value_counts(dropna=False)

monthlyincome
NaN          489
2342,59$     228
4492,84$     227
8339,32$     105
12783,92$     42
            ... 
3018,33$       1
5330,83$       1
4994,17$       1
3806,67$       1
3705,83$       1
Name: count, Length: 494, dtype: int64

In [85]:
df['monthlyincome'].unique()

array(['16280,83$', nan, '14307,50$', '12783,92$', '14311,67$',
       '8339,32$', '13829,17$', '15943,72$', '16644,17$', '15034,17$',
       '16038,33$', '4492,84$', '8956,67$', '5167,50$', '3334,17$',
       '8705,83$', '2675,00$', '8555,00$', '8729,17$', '3934,17$',
       '3845,83$', '14132,50$', '8588,33$', '4505,00$', '4918,33$',
       '4928,33$', '5538,33$', '11100,00$', '5572,50$', '11560,00$',
       '15870,83$', '13345,83$', '8010,83$', '3588,33$', '14205,00$',
       '4222,50$', '3076,67$', '2342,59$', '4789,17$', '8685,00$',
       '5289,17$', '1956,67$', '10408,33$', '6683,33$', '7452,50$',
       '16060,00$', '4647,50$', '2242,50$', '6169,17$', '7352,50$',
       '2982,50$', '14815,83$', '15177,50$', '15991,67$', '15989,17$',
       '8340,00$', '6656,67$', '5902,50$', '3935,83$', '2839,17$',
       '2440,83$', '10025,83$', '12855,83$', '5135,00$', '4271,67$',
       '8015,83$', '4175,00$', '15860,83$', '8666,67$', '2327,50$',
       '4728,33$', '7010,00$', '2790,00$', '4

In [86]:
df['monthlyrate'].value_counts(dropna=False)

monthlyrate
11681,39$    326
6090,75$     308
21682,23$    150
33238,20$     55
41453,67$     38
            ... 
6721,00$       1
9871,33$       1
9165,00$       1
10527,83$      1
42100,50$      1
Name: count, Length: 673, dtype: int64

In [87]:
df['monthlyrate'].unique()

array(['42330,17$', '43331,17$', '41669,33$', '37199,50$', '33238,20$',
       '37210,33$', '21682,23$', '11681,39$', '35955,83$', '41453,67$',
       '43274,83$', '29037,67$', '28613,00$', '42347,50$', '39088,83$',
       '41699,67$', '23287,33$', '36296,00$', '13435,50$', '42997,50$',
       '8668,83$', '22635,17$', '34805,33$', '6955,00$', '22243,00$',
       '22695,83$', '13351,00$', '10228,83$', '6090,75$', '9999,17$',
       '36744,50$', '22329,67$', '11713,00$', '12787,67$', '23519,17$',
       '12813,67$', '14399,67$', '30274,83$', '28860,00$', '14488,50$',
       '10259,17$', '30056,00$', '41264,17$', '34699,17$', '20828,17$',
       '24938,33$', '9329,67$', '36933,00$', '10978,50$', '7999,33$',
       '43001,83$', '5000,67$', '12451,83$', '22581,00$', '13751,83$',
       '5087,33$', '6656,00$', '27061,67$', '17376,67$', '36980,67$',
       '19376,50$', '41756,00$', '12083,50$', '5830,50$', '16039,83$',
       '19116,50$', '7754,50$', '38521,17$', '39461,50$', '29416,83$',
   

In [88]:
# Metodo para cambiar el tipo de una columna

# df['age'].astype(int)