In [ ]:
import numpy as np
import pandas as pd
pd.set_option('display.max_columns', None)  # Esto es para ver todas las columnas de un dataframe
# pd.set_option('display.max_rows', None)     # Esto es para ver todas las filas de un dataframe

In [22]:
df = pd.read_csv('../datos/hr_raw_data_final.csv', index_col=0)

df.head()

age attrition businesstravel    dailyrate                department  \
0  51        No            NaN  2015.722222                       NaN   
1  52        No            NaN  2063.388889                       NaN   
2  42        No  travel_rarely  1984.253968   Research & Development    
3  47        No  travel_rarely  1771.404762                       NaN   
4  46        No            NaN  1582.771346                       NaN   

   distancefromhome  education    educationfield  employeecount  \
0                 6          3               NaN              1   
1                 1          4     Life Sciences              1   
2                 4          2  Technical Degree              1   
3                 2          4           Medical              1   
4                 3          3  Technical Degree              1   

   employeenumber  environmentsatisfaction  gender  hourlyrate  \
0               1                        1       0         NaN   
1               2                        3       0         NaN   
2               3                        3       0         NaN   
3               4                        1       1         NaN   
4               5                        1       1         NaN   

   jobinvolvement  joblevel              jobrole  jobsatisfaction  \
0               3         5   resEArch DIREcToR                 3   
1               2         5             ManAGeR                 3   
2               3         5             ManaGER                 4   
3               3         4   ReseArCH DIrECtOr                 3   
4               4         4     sAleS EXECUtIve                 1   

  maritalstatus monthlyincome monthlyrate  numcompaniesworked over18 overtime  \
0           NaN     16280,83$   42330,17$                   7      Y       No   
1           NaN           NaN   43331,17$                   0    NaN      NaN   
2       Married           NaN   41669,33$                   1    NaN       No   
3       Married     14307,50$   37199,50$                   3      Y      NaN   
4      Divorced     12783,92$   33238,20$                   2      Y       No   

   percentsalaryhike performancerating  relationshipsatisfaction  \
0                 13               3,0                         3   
1                 14               3,0                         1   
2                 11               3,0                         4   
3                 19               3,0                         2   
4                 12               3,0                         4   

  standardhours  stockoptionlevel totalworkingyears  trainingtimeslastyear  \
0     Full Time                 0               NaN                      5   
1           NaN                 1              34,0                      5   
2           NaN                 0              22,0                      3   
3     Full Time                 2               NaN                      2   
4           NaN                 1               NaN                      5   

  worklifebalance  yearsatcompany yearsincurrentrole  yearssincelastpromotion  \
0             3,0              20                NaN                       15   
1             3,0              33                NaN                       11   
2             NaN              22                NaN                       11   
3             NaN              20                NaN                        5   
4             3,0              19                NaN                        2   

   yearswithcurrmanager sameasmonthlyincome  datebirth      salary  \
0                    15           16280,83$       1972  195370,00$   
1                     9                 NaN       1971  199990,00$   
2                    15                 NaN       1981  192320,00$   
3                     6           14307,50$       1976  171690,00$   
4                     8           12783,92$       1977         NaN   

                        roledepartament  numberchildren remotework  
0     

In [ ]:
# Columnas y filas
df.shape

(1678, 41)

In [ ]:
# Tamaño del Dataframe
df.size

68798

In [ ]:
# Todas las columnas
df.columns

Index(['age', 'attrition', 'businesstravel', 'dailyrate', 'department',
       'distancefromhome', 'education', 'educationfield', 'employeecount',
       'employeenumber', 'environmentsatisfaction', 'gender', 'hourlyrate',
       'jobinvolvement', 'joblevel', 'jobrole', 'jobsatisfaction',
       'maritalstatus', 'monthlyincome', 'monthlyrate', 'numcompaniesworked',
       'over18', 'overtime', 'percentsalaryhike', 'performancerating',
       'relationshipsatisfaction', 'standardhours', 'stockoptionlevel',
       'totalworkingyears', 'trainingtimeslastyear', 'worklifebalance',
       'yearsatcompany', 'yearsincurrentrole', 'yearssincelastpromotion',
       'yearswithcurrmanager', 'sameasmonthlyincome', 'datebirth', 'salary',
       'roledepartament', 'numberchildren', 'remotework'],
      dtype='object')

In [ ]:
# Tipos de datos de cada columna

df.dtypes

age                          object
attrition                    object
businesstravel               object
dailyrate                   float64
department                   object
distancefromhome              int64
education                     int64
educationfield               object
employeecount                 int64
employeenumber                int64
environmentsatisfaction       int64
gender                        int64
hourlyrate                  float64
jobinvolvement                int64
joblevel                      int64
jobrole                      object
jobsatisfaction               int64
maritalstatus                object
monthlyincome                object
monthlyrate                  object
numcompaniesworked            int64
over18                       object
overtime                     object
percentsalaryhike             int64
performancerating            object
relationshipsatisfaction      int64
standardhours                object
stockoptionlevel            

In [35]:
df['gender'].unique()

array([0, 1])

In [34]:
df['environmentsatisfaction'].unique()

array([ 1,  3,  4,  2, 42, 37, 35, 25, 27, 31, 39, 21, 15, 14, 33, 19, 12,
       13, 28, 47, 36, 29, 24, 46, 16, 22, 41, 49, 11, 48, 18, 10, 45, 38,
       17, 20, 26, 43])

In [33]:
df['employeenumber'].unique()

array([   1,    2,    3, ..., 1612, 1613, 1614])

In [32]:
df['employeecount'].unique()

array([1])

In [29]:
df['educationfield'].unique()

array([nan, 'Life Sciences', 'Technical Degree', 'Medical', 'Other',
       'Marketing', 'Human Resources'], dtype=object)

In [30]:
df.isna().sum()

age                            0
attrition                      0
businesstravel               801
dailyrate                      0
department                  1366
distancefromhome               0
education                      0
educationfield               774
employeecount                  0
employeenumber                 0
environmentsatisfaction        0
gender                         0
hourlyrate                  1267
jobinvolvement                 0
joblevel                       0
jobrole                        0
jobsatisfaction                0
maritalstatus                675
monthlyincome                489
monthlyrate                    0
numcompaniesworked             0
over18                       938
overtime                     696
percentsalaryhike              0
performancerating            200
relationshipsatisfaction       0
standardhours                351
stockoptionlevel               0
totalworkingyears            549
trainingtimeslastyear          0
worklifeba

In [ ]:
# Valores unicos de la columna 'AGE'

df['age'].unique()

array(['51', '52', '42', '47', '46', '48', '59', '41', '56', '38', '55',
       '40', '58', '35', '45', '33', '36', '34', 'forty-seven', '53',
       '43', '60', '32', '37', '49', '39', '50', '44', '30',
       'fifty-eight', '29', '31', '54', '57', '27', 'thirty-six', '28',
       '26', 'fifty-five', '25', 'fifty-two', 'thirty-one', '24',
       'thirty', '23', '22', '21', '20', 'twenty-six', '19',
       'thirty-seven', '18', 'thirty-two', 'twenty-four'], dtype=object)

In [ ]:

df['attrition'].unique()

array(['No', 'Yes'], dtype=object)

In [24]:
df['businesstravel'].unique()

array([nan, 'travel_rarely', 'travel_frequently', 'non-travel'],
      dtype=object)

In [31]:
df['dailyrate'].unique()

array([2015.72222222, 2063.38888889, 1984.25396825, 1771.4047619 ,
       1582.77134647, 1771.92063492, 1032.48728618,  556.256661  ,
       1712.18253968, 1973.98412698, 2060.70634921, 1382.74603175,
       1362.52380952, 2016.54761905, 1861.37301587, 1985.6984127 ,
       1108.92063492, 1728.38095238,  639.78571429, 2047.5       ,
        412.8015873 , 1077.86507937, 1657.3968254 ,  331.19047619,
       1059.19047619, 1080.75396825,  635.76190476,  487.08730159,
        290.03550974,  476.15079365, 1749.73809524, 1063.31746032,
        557.76190476,  608.93650794, 1119.96031746,  610.17460317,
        685.6984127 , 1441.65873016, 1374.28571429,  689.92857143,
        488.53174603, 1431.23809524, 1964.96031746, 1652.34126984,
        991.81746032, 1187.53968254,  444.26984127, 1758.71428571,
        522.78571429,  380.92063492, 2047.70634921,  238.12698413,
        592.94444444, 1075.28571429,  654.84920635,  242.25396825,
        316.95238095, 1288.65079365,  827.46031746, 1760.98412

In [26]:
df['department'].unique()

array([nan, ' Research & Development ', ' Sales ', ' Human Resources '],
      dtype=object)

In [27]:
df['distancefromhome'].unique()

array([  6,   1,   4,   2,   3,  22,  25,   9,   7,  23,  10,  12,  14,
       -13,  15,   8, -42,  28, -37,   5,  16, -35,  26, -26,  24,  29,
       -25,  17,  21, -18, -10, -30, -27,  20, -31, -29, -39,  18, -21,
       -15,  11,  13, -14,  19, -33, -34, -46, -36, -19,  27, -12, -23,
       -45, -28, -47, -32, -24, -16, -22, -41, -49, -11, -48, -38, -20,
       -17, -43, -40, -44])

In [28]:
df['education'].unique()

array([3, 4, 2, 1, 5])

In [ ]:
# Metodo para cambiar el tipo de una columna

# df['age'].astype(int)

ValueError: invalid literal for int() with base 10: 'forty-seven'