In [10]:
import numpy as np
import pandas as pd
pd.set_option('display.max_columns', None)  # Esto es para ver todas las columnas de un dataframe
# pd.set_option('display.max_rows', None)     # Esto es para ver todas las filas de un dataframe

from datetime import datetime

In [2]:
df = pd.read_csv('../datos/hr_raw_data_final.csv', index_col=0)

df.head()

age attrition businesstravel    dailyrate                department  \
0  51        No            NaN  2015.722222                       NaN   
1  52        No            NaN  2063.388889                       NaN   
2  42        No  travel_rarely  1984.253968   Research & Development    
3  47        No  travel_rarely  1771.404762                       NaN   
4  46        No            NaN  1582.771346                       NaN   

   distancefromhome  education    educationfield  employeecount  \
0                 6          3               NaN              1   
1                 1          4     Life Sciences              1   
2                 4          2  Technical Degree              1   
3                 2          4           Medical              1   
4                 3          3  Technical Degree              1   

   employeenumber  environmentsatisfaction  gender  hourlyrate  \
0               1                        1       0         NaN   
1               2                        3       0         NaN   
2               3                        3       0         NaN   
3               4                        1       1         NaN   
4               5                        1       1         NaN   

   jobinvolvement  joblevel              jobrole  jobsatisfaction  \
0               3         5   resEArch DIREcToR                 3   
1               2         5             ManAGeR                 3   
2               3         5             ManaGER                 4   
3               3         4   ReseArCH DIrECtOr                 3   
4               4         4     sAleS EXECUtIve                 1   

  maritalstatus monthlyincome monthlyrate  numcompaniesworked over18 overtime  \
0           NaN     16280,83$   42330,17$                   7      Y       No   
1           NaN           NaN   43331,17$                   0    NaN      NaN   
2       Married           NaN   41669,33$                   1    NaN       No   
3       Married     14307,50$   37199,50$                   3      Y      NaN   
4      Divorced     12783,92$   33238,20$                   2      Y       No   

   percentsalaryhike performancerating  relationshipsatisfaction  \
0                 13               3,0                         3   
1                 14               3,0                         1   
2                 11               3,0                         4   
3                 19               3,0                         2   
4                 12               3,0                         4   

  standardhours  stockoptionlevel totalworkingyears  trainingtimeslastyear  \
0     Full Time                 0               NaN                      5   
1           NaN                 1              34,0                      5   
2           NaN                 0              22,0                      3   
3     Full Time                 2               NaN                      2   
4           NaN                 1               NaN                      5   

  worklifebalance  yearsatcompany yearsincurrentrole  yearssincelastpromotion  \
0             3,0              20                NaN                       15   
1             3,0              33                NaN                       11   
2             NaN              22                NaN                       11   
3             NaN              20                NaN                        5   
4             3,0              19                NaN                        2   

   yearswithcurrmanager sameasmonthlyincome  datebirth      salary  \
0                    15           16280,83$       1972  195370,00$   
1                     9                 NaN       1971  199990,00$   
2                    15                 NaN       1981  192320,00$   
3                     6           14307,50$       1976  171690,00$   
4                     8           12783,92$       1977         NaN   

                        roledepartament  numberchildren remotework  
0     

In [ ]:
# Hay 64 filas repetidas.
df.duplicated().sum()


64

In [5]:
# Esto es para borrar los duplicados y mantener el original 

df_sin_duplicados = df.drop_duplicates(keep='last')

df_sin_duplicados.head()

age attrition businesstravel    dailyrate                department  \
0  51        No            NaN  2015.722222                       NaN   
1  52        No            NaN  2063.388889                       NaN   
2  42        No  travel_rarely  1984.253968   Research & Development    
3  47        No  travel_rarely  1771.404762                       NaN   
4  46        No            NaN  1582.771346                       NaN   

   distancefromhome  education    educationfield  employeecount  \
0                 6          3               NaN              1   
1                 1          4     Life Sciences              1   
2                 4          2  Technical Degree              1   
3                 2          4           Medical              1   
4                 3          3  Technical Degree              1   

   employeenumber  environmentsatisfaction  gender  hourlyrate  \
0               1                        1       0         NaN   
1               2                        3       0         NaN   
2               3                        3       0         NaN   
3               4                        1       1         NaN   
4               5                        1       1         NaN   

   jobinvolvement  joblevel              jobrole  jobsatisfaction  \
0               3         5   resEArch DIREcToR                 3   
1               2         5             ManAGeR                 3   
2               3         5             ManaGER                 4   
3               3         4   ReseArCH DIrECtOr                 3   
4               4         4     sAleS EXECUtIve                 1   

  maritalstatus monthlyincome monthlyrate  numcompaniesworked over18 overtime  \
0           NaN     16280,83$   42330,17$                   7      Y       No   
1           NaN           NaN   43331,17$                   0    NaN      NaN   
2       Married           NaN   41669,33$                   1    NaN       No   
3       Married     14307,50$   37199,50$                   3      Y      NaN   
4      Divorced     12783,92$   33238,20$                   2      Y       No   

   percentsalaryhike performancerating  relationshipsatisfaction  \
0                 13               3,0                         3   
1                 14               3,0                         1   
2                 11               3,0                         4   
3                 19               3,0                         2   
4                 12               3,0                         4   

  standardhours  stockoptionlevel totalworkingyears  trainingtimeslastyear  \
0     Full Time                 0               NaN                      5   
1           NaN                 1              34,0                      5   
2           NaN                 0              22,0                      3   
3     Full Time                 2               NaN                      2   
4           NaN                 1               NaN                      5   

  worklifebalance  yearsatcompany yearsincurrentrole  yearssincelastpromotion  \
0             3,0              20                NaN                       15   
1             3,0              33                NaN                       11   
2             NaN              22                NaN                       11   
3             NaN              20                NaN                        5   
4             3,0              19                NaN                        2   

   yearswithcurrmanager sameasmonthlyincome  datebirth      salary  \
0                    15           16280,83$       1972  195370,00$   
1                     9                 NaN       1971  199990,00$   
2                    15                 NaN       1981  192320,00$   
3                     6           14307,50$       1976  171690,00$   
4                     8           12783,92$       1977         NaN   

                        roledepartament  numberchildren remotework  
0     

In [6]:
df_sin_duplicados.duplicated().sum()


0

Duplicados borrados

In [7]:
df = df.drop_duplicates(keep='last')

In [8]:
df.duplicated().sum()

0

Añadir la edad en las celdas que no tenian

In [11]:

current_year = datetime.now().year
df['age'] = current_year - df['datebirth']
df['age']

0       52
1       53
2       43
3       48
4       47
        ..
1673    44
1674    48
1675    30
1676    48
1677    33
Name: age, Length: 1614, dtype: int64

In [12]:
df['age'].isnull().sum()

0

Cambiar los vacios de business travel

In [17]:
df['businesstravel'] = df['businesstravel'].replace(np.nan, 'non-travel')

In [18]:
df['businesstravel'].unique()

array(['non-travel', 'travel_rarely', 'travel_frequently'], dtype=object)

Convertir la columna 'DailyRate' de string a tipo numérico (float)

In [21]:
# Convertir la columna 'DailyRate' de string a tipo numérico (float)
df['dailyrate'] = pd.to_numeric(df['dailyrate'], errors='coerce')
df['dailyrate'].round(2)

0       2015.72
1       2063.39
2       1984.25
3       1771.40
4       1582.77
         ...   
1673     488.94
1674    1973.98
1675     290.04
1676    1032.49
1677     556.26
Name: dailyrate, Length: 1614, dtype: float64

Columna de 'department' - Gestión de nulos: poner 'Unknow'

In [22]:
df['department'].isnull().sum()

1312

In [30]:
df['department'].describe()

count                          302
unique                           3
top        Research & Development 
freq                           196
Name: department, dtype: object

In [32]:
df['department'].unique()

array([nan, ' Research & Development ', ' Sales ', ' Human Resources '],
      dtype=object)

Columna 'distancefromhome' - Poner los valores en modulo

In [33]:
# Cambiar los valores de distancia from home a un modulo, o sea, no tener más los negativos

df["distancefromhome"] = df["distancefromhome"].abs()

In [35]:
df["distancefromhome"].isnull().sum()

0

Columna 'educationfield' - Gestión de Nulos: Poner como 'Unkonw ya que el porcentaje de 'life sciences' y 'Medical' es muy similar una a la otra.

In [36]:
df['educationfield'].isnull().sum()

745

In [38]:
df['educationfield'].describe()

count               869
unique                6
top       Life Sciences
freq                349
Name: educationfield, dtype: object

In [39]:
df['educationfield'].unique()

array([nan, 'Life Sciences', 'Technical Degree', 'Medical', 'Other',
       'Marketing', 'Human Resources'], dtype=object)

In [40]:
(df['educationfield'].value_counts() / df.shape[0])

educationfield
Life Sciences       0.216233
Medical             0.171004
Marketing           0.064436
Technical Degree    0.042751
Other               0.036555
Human Resources     0.007435
Name: count, dtype: float64

In [41]:
df['environmentsatisfaction'].unique()

array([ 1,  3,  4,  2, 42, 37, 35, 25, 27, 31, 39, 21, 15, 14, 33, 19, 12,
       13, 28, 47, 36, 29, 24, 46, 16, 22, 41, 49, 11, 48, 18, 10, 45, 38,
       17, 20, 26, 43])